// 
// FLImportedTestObject.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp
// Schema: FLTestObjects
// 
// Generated by: Mike Fullerton @ 5/21/13 9:17 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC (http://www.greentongue.com)
// 
// License: Individual licensees only.
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLImportedTestObject.h"
@implementation FLImportedTestObject
@synthesize sanjo = _sanjo;
@synthesize chloe = _chloe;
@synthesize teddy = _teddy;
+(FLImportedTestObject*) importedTestObject {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_sanjo release];
    [_chloe release];
    [_teddy release];
    [super dealloc];
}
#endif
@end
