// 
// FLTwitterError.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp
// Schema: FishLampTwitter
// 
// Generated by: Mike Fullerton @ 5/12/13 7:56 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. 
//  The FishLamp Framework is released under the MIT License: http://fishlamp.com/license 
// 
#import "FLModelObject.h"
@interface FLTwitterError : FLModelObject {
@private
    NSString* _error;
    NSString* _request;
}

@property (readwrite, strong, nonatomic) NSString* error;
@property (readwrite, strong, nonatomic) NSString* request;
+(FLTwitterError) error;
@end
