// 
// FLTwitterError.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp
// Schema: FishLampTwitter
// 
// Generated by: Mike Fullerton @ 5/12/13 7:56 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. 
//  The FishLamp Framework is released under the MIT License: http://fishlamp.com/license 
// 
#import "FLTwitterError.h"
@implementation FLTwitterError
@synthesize error = _error;
@synthesize request = _request;
+(FLTwitterError) error {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_error release];
    [_request release];
    [super dealloc];
}
#endif
@end
