// 
// ZFApiSoap.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFApiSoapDeletePhotos.h"
#import "ZFApiSoapUpdateGroup.h"
#import "ZFApiSoapLoadPublicProfile.h"
#import "ZFApiSoapGetVisitorKey.h"
#import "ZFApiSoapUpdatePhoto.h"
#import "ZFApiSoapAuthenticate.h"
#import "ZFApiSoapUndeleteMessage.h"
#import "ZFApiSoapLoadGroup.h"
#import "ZFApiSoapLoadGroupHierarchy.h"
#import "ZFApiSoapCheckPrivilege.h"
#import "ZFApiSoapRotatePhoto.h"
#import "ZFApiSoapCreateGroup.h"
#import "ZFApiSoapResolveReference.h"
#import "ZFApiSoapKeyringAddKeyPlain.h"
#import "ZFApiSoapSearchSetByText.h"
#import "ZFApiSoapCreateVideoFromUrl.h"
#import "ZFApiSoapSetPhotoSetFeaturedIndex.h"
#import "ZFApiSoapReindexPhotoSet.h"
#import "ZFApiSoapKeyringGetUnlockedRealms.h"
#import "ZFApiSoapLoadPhoto.h"
#import "ZFApiSoapSearchSetByCategory.h"
#import "ZFApiSoapCollectionAddPhoto.h"
#import "ZFApiSoapMovePhotos.h"
#import "ZFApiSoapGetCategories.h"
#import "ZFApiSoapLoadAccessRealm.h"
#import "ZFApiSoapLoadMessages.h"
#import "ZFApiSoapMoveGroup.h"
#import "ZFApiSoapLoadSharedFavoritesSets.h"
#import "ZFApiSoapAuthenticateVisitor.h"
#import "ZFApiSoapAuthenticatePlain.h"
#import "ZFApiSoapCollectionRemovePhoto.h"
#import "ZFApiSoapReorderPhotoSet.h"
#import "ZFApiSoapGetPopularPhotos.h"
#import "ZFApiSoapGetDownloadOriginalKey.h"
#import "ZFApiSoapUpdatePhotoSetAccess.h"
#import "ZFApiSoapSetPhotoSetTitlePhoto.h"
#import "ZFApiSoapGetPopularSets.h"
#import "ZFApiSoapGetRecentPhotos.h"
#import "ZFApiSoapCreateFavoritesSet.h"
#import "ZFApiSoapUpdatePhotoSet.h"
#import "ZFApiSoapGetChallenge.h"
#import "ZFApiSoapGetRecentSets.h"
#import "ZFApiSoapUpdatePhotoAccess.h"
#import "ZFApiSoapMovePhoto.h"
#import "ZFApiSoapCreatePhotoFromUrl.h"
#import "ZFApiSoapSearchPhotoByCategory.h"
#import "ZFApiSoapSearchPhotoByText.h"
#import "ZFApiSoapAddMessage.h"
#import "ZFApiSoapCreateQuickBlogPost.h"
#import "ZFApiSoapShareFavoritesSet.h"
#import "ZFApiSoapSetGroupTitlePhoto.h"
#import "ZFApiSoapLoadPhotoSetPhotos.h"
#import "ZFApiSoapCreatePhotoSet.h"
#import "ZFApiSoapUpdateGroupAccess.h"
#import "ZFApiSoapDeletePhotoSet.h"
#import "ZFApiSoapReplacePhoto.h"
#import "ZFApiSoapLoadPhotoSet.h"
#import "ZFApiSoap.h"
#import "ZFApiSoapReorderGroup.h"
#import "ZFApiSoapGetVideoPlaybackUrl.h"
#import "ZFApiSoapLoadPrivateProfile.h"
#import "ZFApiSoapMovePhotoSet.h"
#import "FLModelObject.h"
#import "ZFApiSoapRemoveGroupTitlePhoto.h"
#import "ZFApiSoapSetRandomPhotoSetTitlePhoto.h"
#import "ZFApiSoapGetVersion.h"
#import "ZFApiSoapDeleteGroup.h"
#import "ZFApiSoapDeletePhoto.h"
#import "ZFApiSoapRemovePhotoSetTitlePhoto.h"
#import "ZFApiSoapDeleteMessage.h"

@implementation ZFApiSoap

+ (ZFApiSoap*) apiSoap {
    return FLAutorelease([[[self class] alloc] init]);
}
- (ZFApiSoapAddMessage*) createAddMessage {
    return FLAutorelease([[ZFApiSoapAddMessage alloc] init]);
}
- (ZFApiSoapAuthenticate*) createAuthenticate {
    return FLAutorelease([[ZFApiSoapAuthenticate alloc] init]);
}
- (ZFApiSoapAuthenticatePlain*) createAuthenticatePlain {
    return FLAutorelease([[ZFApiSoapAuthenticatePlain alloc] init]);
}
- (ZFApiSoapAuthenticateVisitor*) createAuthenticateVisitor {
    return FLAutorelease([[ZFApiSoapAuthenticateVisitor alloc] init]);
}
- (ZFApiSoapCheckPrivilege*) createCheckPrivilege {
    return FLAutorelease([[ZFApiSoapCheckPrivilege alloc] init]);
}
- (ZFApiSoapCollectionAddPhoto*) createCollectionAddPhoto {
    return FLAutorelease([[ZFApiSoapCollectionAddPhoto alloc] init]);
}
- (ZFApiSoapCollectionRemovePhoto*) createCollectionRemovePhoto {
    return FLAutorelease([[ZFApiSoapCollectionRemovePhoto alloc] init]);
}
- (ZFApiSoapCreateFavoritesSet*) createCreateFavoritesSet {
    return FLAutorelease([[ZFApiSoapCreateFavoritesSet alloc] init]);
}
- (ZFApiSoapCreateGroup*) createCreateGroup {
    return FLAutorelease([[ZFApiSoapCreateGroup alloc] init]);
}
- (ZFApiSoapCreatePhotoFromUrl*) createCreatePhotoFromUrl {
    return FLAutorelease([[ZFApiSoapCreatePhotoFromUrl alloc] init]);
}
- (ZFApiSoapCreatePhotoSet*) createCreatePhotoSet {
    return FLAutorelease([[ZFApiSoapCreatePhotoSet alloc] init]);
}
- (ZFApiSoapCreateQuickBlogPost*) createCreateQuickBlogPost {
    return FLAutorelease([[ZFApiSoapCreateQuickBlogPost alloc] init]);
}
- (ZFApiSoapCreateVideoFromUrl*) createCreateVideoFromUrl {
    return FLAutorelease([[ZFApiSoapCreateVideoFromUrl alloc] init]);
}
- (ZFApiSoapDeleteGroup*) createDeleteGroup {
    return FLAutorelease([[ZFApiSoapDeleteGroup alloc] init]);
}
- (ZFApiSoapDeleteMessage*) createDeleteMessage {
    return FLAutorelease([[ZFApiSoapDeleteMessage alloc] init]);
}
- (ZFApiSoapDeletePhoto*) createDeletePhoto {
    return FLAutorelease([[ZFApiSoapDeletePhoto alloc] init]);
}
- (ZFApiSoapDeletePhotoSet*) createDeletePhotoSet {
    return FLAutorelease([[ZFApiSoapDeletePhotoSet alloc] init]);
}
- (ZFApiSoapDeletePhotos*) createDeletePhotos {
    return FLAutorelease([[ZFApiSoapDeletePhotos alloc] init]);
}
- (ZFApiSoapGetCategories*) createGetCategories {
    return FLAutorelease([[ZFApiSoapGetCategories alloc] init]);
}
- (ZFApiSoapGetChallenge*) createGetChallenge {
    return FLAutorelease([[ZFApiSoapGetChallenge alloc] init]);
}
- (ZFApiSoapGetDownloadOriginalKey*) createGetDownloadOriginalKey {
    return FLAutorelease([[ZFApiSoapGetDownloadOriginalKey alloc] init]);
}
- (ZFApiSoapGetPopularPhotos*) createGetPopularPhotos {
    return FLAutorelease([[ZFApiSoapGetPopularPhotos alloc] init]);
}
- (ZFApiSoapGetPopularSets*) createGetPopularSets {
    return FLAutorelease([[ZFApiSoapGetPopularSets alloc] init]);
}
- (ZFApiSoapGetRecentPhotos*) createGetRecentPhotos {
    return FLAutorelease([[ZFApiSoapGetRecentPhotos alloc] init]);
}
- (ZFApiSoapGetRecentSets*) createGetRecentSets {
    return FLAutorelease([[ZFApiSoapGetRecentSets alloc] init]);
}
- (ZFApiSoapGetVersion*) createGetVersion {
    return FLAutorelease([[ZFApiSoapGetVersion alloc] init]);
}
- (ZFApiSoapGetVideoPlaybackUrl*) createGetVideoPlaybackUrl {
    return FLAutorelease([[ZFApiSoapGetVideoPlaybackUrl alloc] init]);
}
- (ZFApiSoapGetVisitorKey*) createGetVisitorKey {
    return FLAutorelease([[ZFApiSoapGetVisitorKey alloc] init]);
}
- (ZFApiSoapKeyringAddKeyPlain*) createKeyringAddKeyPlain {
    return FLAutorelease([[ZFApiSoapKeyringAddKeyPlain alloc] init]);
}
- (ZFApiSoapKeyringGetUnlockedRealms*) createKeyringGetUnlockedRealms {
    return FLAutorelease([[ZFApiSoapKeyringGetUnlockedRealms alloc] init]);
}
- (ZFApiSoapLoadAccessRealm*) createLoadAccessRealm {
    return FLAutorelease([[ZFApiSoapLoadAccessRealm alloc] init]);
}
- (ZFApiSoapLoadGroup*) createLoadGroup {
    return FLAutorelease([[ZFApiSoapLoadGroup alloc] init]);
}
- (ZFApiSoapLoadGroupHierarchy*) createLoadGroupHierarchy {
    return FLAutorelease([[ZFApiSoapLoadGroupHierarchy alloc] init]);
}
- (ZFApiSoapLoadMessages*) createLoadMessages {
    return FLAutorelease([[ZFApiSoapLoadMessages alloc] init]);
}
- (ZFApiSoapLoadPhoto*) createLoadPhoto {
    return FLAutorelease([[ZFApiSoapLoadPhoto alloc] init]);
}
- (ZFApiSoapLoadPhotoSet*) createLoadPhotoSet {
    return FLAutorelease([[ZFApiSoapLoadPhotoSet alloc] init]);
}
- (ZFApiSoapLoadPhotoSetPhotos*) createLoadPhotoSetPhotos {
    return FLAutorelease([[ZFApiSoapLoadPhotoSetPhotos alloc] init]);
}
- (ZFApiSoapLoadPrivateProfile*) createLoadPrivateProfile {
    return FLAutorelease([[ZFApiSoapLoadPrivateProfile alloc] init]);
}
- (ZFApiSoapLoadPublicProfile*) createLoadPublicProfile {
    return FLAutorelease([[ZFApiSoapLoadPublicProfile alloc] init]);
}
- (ZFApiSoapLoadSharedFavoritesSets*) createLoadSharedFavoritesSets {
    return FLAutorelease([[ZFApiSoapLoadSharedFavoritesSets alloc] init]);
}
- (ZFApiSoapMoveGroup*) createMoveGroup {
    return FLAutorelease([[ZFApiSoapMoveGroup alloc] init]);
}
- (ZFApiSoapMovePhoto*) createMovePhoto {
    return FLAutorelease([[ZFApiSoapMovePhoto alloc] init]);
}
- (ZFApiSoapMovePhotoSet*) createMovePhotoSet {
    return FLAutorelease([[ZFApiSoapMovePhotoSet alloc] init]);
}
- (ZFApiSoapMovePhotos*) createMovePhotos {
    return FLAutorelease([[ZFApiSoapMovePhotos alloc] init]);
}
- (ZFApiSoapReindexPhotoSet*) createReindexPhotoSet {
    return FLAutorelease([[ZFApiSoapReindexPhotoSet alloc] init]);
}
- (ZFApiSoapRemoveGroupTitlePhoto*) createRemoveGroupTitlePhoto {
    return FLAutorelease([[ZFApiSoapRemoveGroupTitlePhoto alloc] init]);
}
- (ZFApiSoapRemovePhotoSetTitlePhoto*) createRemovePhotoSetTitlePhoto {
    return FLAutorelease([[ZFApiSoapRemovePhotoSetTitlePhoto alloc] init]);
}
- (ZFApiSoapReorderGroup*) createReorderGroup {
    return FLAutorelease([[ZFApiSoapReorderGroup alloc] init]);
}
- (ZFApiSoapReorderPhotoSet*) createReorderPhotoSet {
    return FLAutorelease([[ZFApiSoapReorderPhotoSet alloc] init]);
}
- (ZFApiSoapReplacePhoto*) createReplacePhoto {
    return FLAutorelease([[ZFApiSoapReplacePhoto alloc] init]);
}
- (ZFApiSoapResolveReference*) createResolveReference {
    return FLAutorelease([[ZFApiSoapResolveReference alloc] init]);
}
- (ZFApiSoapRotatePhoto*) createRotatePhoto {
    return FLAutorelease([[ZFApiSoapRotatePhoto alloc] init]);
}
- (ZFApiSoapSearchPhotoByCategory*) createSearchPhotoByCategory {
    return FLAutorelease([[ZFApiSoapSearchPhotoByCategory alloc] init]);
}
- (ZFApiSoapSearchPhotoByText*) createSearchPhotoByText {
    return FLAutorelease([[ZFApiSoapSearchPhotoByText alloc] init]);
}
- (ZFApiSoapSearchSetByCategory*) createSearchSetByCategory {
    return FLAutorelease([[ZFApiSoapSearchSetByCategory alloc] init]);
}
- (ZFApiSoapSearchSetByText*) createSearchSetByText {
    return FLAutorelease([[ZFApiSoapSearchSetByText alloc] init]);
}
- (ZFApiSoapSetGroupTitlePhoto*) createSetGroupTitlePhoto {
    return FLAutorelease([[ZFApiSoapSetGroupTitlePhoto alloc] init]);
}
- (ZFApiSoapSetPhotoSetFeaturedIndex*) createSetPhotoSetFeaturedIndex {
    return FLAutorelease([[ZFApiSoapSetPhotoSetFeaturedIndex alloc] init]);
}
- (ZFApiSoapSetPhotoSetTitlePhoto*) createSetPhotoSetTitlePhoto {
    return FLAutorelease([[ZFApiSoapSetPhotoSetTitlePhoto alloc] init]);
}
- (ZFApiSoapSetRandomPhotoSetTitlePhoto*) createSetRandomPhotoSetTitlePhoto {
    return FLAutorelease([[ZFApiSoapSetRandomPhotoSetTitlePhoto alloc] init]);
}
- (ZFApiSoapShareFavoritesSet*) createShareFavoritesSet {
    return FLAutorelease([[ZFApiSoapShareFavoritesSet alloc] init]);
}
- (ZFApiSoapUndeleteMessage*) createUndeleteMessage {
    return FLAutorelease([[ZFApiSoapUndeleteMessage alloc] init]);
}
- (ZFApiSoapUpdateGroup*) createUpdateGroup {
    return FLAutorelease([[ZFApiSoapUpdateGroup alloc] init]);
}
- (ZFApiSoapUpdateGroupAccess*) createUpdateGroupAccess {
    return FLAutorelease([[ZFApiSoapUpdateGroupAccess alloc] init]);
}
- (ZFApiSoapUpdatePhoto*) createUpdatePhoto {
    return FLAutorelease([[ZFApiSoapUpdatePhoto alloc] init]);
}
- (ZFApiSoapUpdatePhotoAccess*) createUpdatePhotoAccess {
    return FLAutorelease([[ZFApiSoapUpdatePhotoAccess alloc] init]);
}
- (ZFApiSoapUpdatePhotoSet*) createUpdatePhotoSet {
    return FLAutorelease([[ZFApiSoapUpdatePhotoSet alloc] init]);
}
- (ZFApiSoapUpdatePhotoSetAccess*) createUpdatePhotoSetAccess {
    return FLAutorelease([[ZFApiSoapUpdatePhotoSetAccess alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif
- (NSString*) location {
    return @"http://api.zenfolio.com/api/1.7/zfapi.asmx";;
}
- (NSString*) targetNamespace {
    return @"http://www.zenfolio.com/api/1.7";;
}
- (NSString*) url {
    return @"http://www.zenfolio.com/api/1.7";;
}

@end
