//
//  FishLampiOS.h
//  FishLampiOS
//
//  Generated by Mike Fullerton on 7/17/12 1:09 PM using "Headers" tool
//  Copyright (c) 2012 GreenTongue Software. All rights reserved.
//

#import "FishLampCocoa.h"
#import "FishLampiOSCore.h"

#import "FLTheme.h"

#ifndef UNIT_TEST
#define UNIT_TEST DEBUG
#endif

#ifndef __FL_MEMORY_MONITOR
#define __FL_MEMORY_MONITOR 0
#endif

#ifndef ALLOCATION_HOOKS
#define ALLOCATION_HOOKS __FL_MEMORY_MONITOR
#endif

/*
This is a known bug with the iOS 4.1 SDK and building using LLVM for the iPhone Simulator. You can read all about it in this thread on Apple's Developer Forums.

The recommended solution is to add the following to Other C Flags in your project's build settings: -D__IPHONE_OS_VERSION_MIN_REQUIRED=040100 where you replace 040100 with your deployment target version (030000 for 3.0, for example).
*/

#if __FL_MEMORY_MONITOR
#undef ALLOCATION_HOOKS
#define ALLOCATION_HOOKS 1
#endif

#ifndef __IPHONE_5_0
#warning ERROR! FishLamp Requires iPhone SDK >= 5.0. See FishLampRequired.h for compatibility help.
#endif

#ifndef FL_CUSTOM_CAMERA
	#if TARGET_IPHONE_SIMULATOR
	#define FL_CUSTOM_CAMERA 0
	#else 
	#define FL_CUSTOM_CAMERA 0 //TARGET_OS_EMBEDDED
	#endif
#endif	

