#!/bin/bash

git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Core merge/FishLamp-Objc-Core
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-UnifiedAsync merge/FishLamp-Objc-UnifiedAsync
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Services merge/FishLamp-Objc-Services
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Containers merge/FishLamp-Objc-Containers
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-CodeGenerator merge/FishLamp-Objc-CodeGenerator
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-UnitTestRunner merge/FishLamp-Objc-UnitTestRunner
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-ModelObject merge/FishLamp-Objc-ModelObject
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Networking merge/FishLamp-Objc-Networking
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Encoding merge/FishLamp-Objc-Encoding
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Storage merge/FishLamp-Objc-Storage
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-CommandLineProcessor merge/FishLamp-Objc-CommandLineProcessor
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-ActivityLog merge/FishLamp-Objc-ActivityLog
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Authentication merge/FishLamp-Objc-Authentication
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-CodeBuilder merge/FishLamp-Objc-CodeBuilder
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-ColorUtils merge/FishLamp-Objc-ColorUtils
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-GeometryUtils merge/FishLamp-Objc-GeometryUtils
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-BundleUtils merge/FishLamp-Objc-BundleUtils
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-UnitTests merge/FishLamp-Objc-UnitTests
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Timer merge/FishLamp-Objc-Timer
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Strings merge/FishLamp-Objc-Strings
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Utils merge/FishLamp-Objc-Utils
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Compatibility merge/FishLamp-Objc-Compatibility
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Experimental merge/FishLamp-Objc-Experimental
git submodule add https://www.github.com/FishLamp/FishLamp-External merge/FishLamp-External
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Files merge/FishLamp-Objc-Files
git submodule add https://www.github.com/FishLamp/FishLamp-Images merge/FishLamp-Images
git submodule add https://www.github.com/FishLamp/FishLamp-Objc-Notifications merge/FishLamp-Objc-Notifications
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-ActivityLogViewController merge/FishLamp-OSX-ActivityLogViewController
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-BreadcrumbBarView merge/FishLamp-OSX-BreadcrumbBarView
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-Documents merge/FishLamp-OSX-Documents
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-ErrorViewController merge/FishLamp-OSX-ErrorViewController
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-FileDropTableViewController merge/FishLamp-OSX-FileDropTableViewController
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-HttpController merge/FishLamp-OSX-HttpController
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-TextViewController merge/FishLamp-OSX-TextViewController
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-TextViewLogger merge/FishLamp-OSX-TextViewLogger
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-Utils merge/FishLamp-OSX-Utils
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-ViewController merge/FishLamp-OSX-ViewController
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-Views merge/FishLamp-OSX-Views
git submodule add https://www.github.com/FishLamp/FishLamp-OSX-WizardViewController merge/FishLamp-OSX-WizardViewController
git submodule add https://www.github.com/FishLamp/FishLamp-UI-Animations merge/FishLamp-UI-Animations
git submodule add https://www.github.com/FishLamp/FishLamp-UI-BoxArranger merge/FishLamp-UI-BoxArranger
git submodule add https://www.github.com/FishLamp/FishLamp-UI-Drawable merge/FishLamp-UI-Drawable
git submodule add https://www.github.com/FishLamp/FishLamp-UI-View merge/FishLamp-UI-View
git submodule add https://www.github.com/FishLamp/FishLamp-UI-ViewController merge/FishLamp-UI-ViewController
