// 
// FLFacebookFetchStatusListResponse.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookFetchStatusListResponse.h"
#import "FLFacebookPost.h"
#import "FLModelObject.h"
#import "FLFacebookPagingResponse.h"
#import "FLObjectDescriber.h"
@implementation FLFacebookFetchStatusListResponse
@synthesize data = _data;
@synthesize paging = _paging;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"post" propertyClass:[FLFacebookPost class]] forContainerProperty:@"data"];
}
+(FLFacebookFetchStatusListResponse*) facebookFetchStatusListResponse {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_data release];
    [_paging release];
    [super dealloc];
}
#endif
@end
