// 
// FLFacebookError.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"
@interface FLFacebookError : FLModelObject {
@private
    NSString* _error_reason;
    NSString* _error_description;
    NSString* _externalUrl;
    NSString* _error;
}

@property (readwrite, strong, nonatomic) NSString* error_reason;
@property (readwrite, strong, nonatomic) NSString* error_description;
@property (readwrite, strong, nonatomic) NSString* externalUrl;
@property (readwrite, strong, nonatomic) NSString* error;
+(FLFacebookError*) facebookError;
@end
