// 
// FLFacebookUserReadPermission.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

typedef enum {
    FLFacebookUserReadPermissionAboutMe,
    FLFacebookUserReadPermissionActivities,
    FLFacebookUserReadPermissionBirthday,
    FLFacebookUserReadPermissionCheckins,
    FLFacebookUserReadPermissionEducationHistory,
    FLFacebookUserReadPermissionEvents,
    FLFacebookUserReadPermissionGroups,
    FLFacebookUserReadPermissionHometown,
    FLFacebookUserReadPermissionInterests,
    FLFacebookUserReadPermissionLikes,
    FLFacebookUserReadPermissionLocation,
    FLFacebookUserReadPermissionNotes,
    FLFacebookUserReadPermissionOnlinePresence,
    FLFacebookUserReadPermissionPhotoVideoTags,
    FLFacebookUserReadPermissionPhotos,
    FLFacebookUserReadPermissionRelationships,
    FLFacebookUserReadPermissionRelationshipDetails,
    FLFacebookUserReadPermissionReligionPolitics,
    FLFacebookUserReadPermissionStatus,
    FLFacebookUserReadPermissionVideos,
    FLFacebookUserReadPermissionWebsite,
    FLFacebookUserReadPermissionWorkHistory,
    FLFacebookUserReadPermissionEmail,
    FLFacebookUserReadPermissionFriendLists,
    FLFacebookUserReadPermissionInsights,
    FLFacebookUserReadPermissionMailbox,
    FLFacebookUserReadPermissionRequests,
    FLFacebookUserReadPermissionStream,
    FLFacebookUserReadPermissionXmppLogin,
    FLFacebookUserReadPermissionAdsManagement,
} FLFacebookUserReadPermission;
