// 
// FLCodeElement.m
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/16/13 1:02 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeElementBaseClass.h"
#import "FLCodeElement.h"

@implementation FLCodeElement

- (id) initWithCode:(id) code {
	self = [super init];
	if(self) {
		self.code = code;
	}
	return self;
}

+ (id) codeElement {
    return FLAutorelease([[[self class] alloc] init]);
}

+ (id) codeElement:(id) code {
    return FLAutorelease([[[self class] alloc] initWithCode:code]);
}

#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif

@end
