// 
// FLCodeVar.h
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/16/13 5:01 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeVarBaseClass.h"

@interface FLCodeVar : FLCodeVarBaseClass {
@private
}

+ (id) codeVar;

@end
