// 
// FLCodeProject.h
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/15/13 4:24 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeProjectBaseClass.h"

@class FLCodeProjectLocation;

@interface FLCodeProject : FLCodeProjectBaseClass {
@private
    NSString* _projectPath;
    FLCodeProjectLocation* _projectLocation;
}

@property (readwrite, strong, nonatomic) NSString* projectPath;
@property (readwrite, strong, nonatomic) FLCodeProjectLocation* projectLocation;

@property (readonly, strong, nonatomic) NSString* projectFolderPath;

+ (id) codeProject;

@end
