// 
// FLTestObject.m
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 7/1/13 2:45 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp
// 
// Organization: GreenTongue Software, LLC (http://www.greentongue.com)
// Copyright 2013 (c) GreenTongue Software, LLC
// Individual licensees only
// 

#import "FLTestObject.h"
#import "FLModelObject.h"

@implementation FLTestObject

@end
