//
//  FLObjcFileHeader.m
//  CodeGenerator
//
//  Created by Mike Fullerton on 5/11/13.
//  Copyright (c) 2013 Mike Fullerton. All rights reserved.
//

#import "FLObjcFileHeader.h"
#import "FLAppInfo.h"
#import "FLCodeCodeLicense.h"
#import "FLCodeGeneratorOptions.h"
#import "FLCodeCompany.h"
#import "FLCodeProject.h"
#import "FLObjcCodeBuilder.h"
#import "FLObjcFile.h"

#define kGeneratedFileHeader @"Generated at %@ by %@ (%@)." 

@interface FLObjcFileHeader ()
@property (readwrite, strong, nonatomic) FLCodeProject* codeProject;
@end

@implementation FLObjcFileHeader

@synthesize codeProject = _codeProject;

+ (id) objcFileHeader:(FLObjcTypeIndex*) typeIndex {
    return FLAutorelease([[[self class] alloc] initWithTypeIndex:typeIndex]);
}

#if FL_MRC
- (void) dealloc {
    [_codeProject release];
    [super dealloc];
}
#endif

- (void) configureWithCodeProject:(FLCodeProject*) codeProject {
    self.codeProject = codeProject;
}

- (void) writeCodeToFile:(FLObjcFile*) file withCodeBuilder:(FLObjcCodeBuilder*) codeBuilder {


    NSDateFormatter *dateFormatter = FLAutorelease([[NSDateFormatter alloc] init]);
    [dateFormatter setDateStyle:kCFDateFormatterShortStyle];
    [dateFormatter setTimeStyle:kCFDateFormatterShortStyle];

    NSString *formattedDateString = [dateFormatter stringFromDate:[NSDate date]];

    FLObjcComment* comment = [FLObjcComment objcComment];
    [comment appendEmptyComment];
	[comment appendLineWithFormat:@"%@", file.fileName];
    [comment appendEmptyComment];
    [comment appendLine:@"DO NOT MODIFY!! Modifications will be overwritten."];
    [comment appendEmptyComment];
	[comment appendLineWithFormat:@"Project: %@", self.codeProject.projectName];
	[comment appendLineWithFormat:@"Schema: %@", self.codeProject.schemaName];
	[comment appendEmptyComment];
	[comment appendLineWithFormat:@"Generated by: %@ @ %@ with %@ (%@)", NSFullUserName(), formattedDateString, [FLAppInfo appName], [FLAppInfo appVersion]];
    
    FLCodeCompany* company = self.codeProject.organization;
    
    if(company) {
        if(FLStringIsNotEmpty(company.name)) {
            [comment appendEmptyComment];
            
            if(FLStringIsNotEmpty(company.website)) {
                [comment appendLineWithFormat:@"Organization: %@ (%@)", company.name, company.website];
            }
            else {
                [comment appendLineWithFormat:@"Organization: %@", company.name];
            }
        }
        
    }
	
    FLCodeCodeLicense* codeLicense = self.codeProject.license;
    if(codeLicense) {
        if(FLStringIsNotEmpty(codeLicense.licenseName)) {
            [comment appendEmptyComment];
            [comment appendLineWithFormat:@"License: %@", codeLicense.licenseName];
        }
        if(FLStringIsNotEmpty(codeLicense.licenseShortDescription)) {
            [comment appendLineWithFormat:@"License Description: %@", codeLicense.licenseName];
        }
        if(FLStringIsNotEmpty(codeLicense.licenseTextFilePath)) {
            [comment appendLineWithFormat:@"License File: %@", codeLicense.licenseTextFilePath];
        }

    }
    [comment appendEmptyComment];
	
// TODO: get current year from system of course
    
    [comment appendLineWithFormat:@"Copywrite (C) 2013 %@. All rights reserved.", self.codeProject.organization.name];
    [comment appendEmptyComment];
    
    [codeBuilder addCodeChunk:comment];
    
	if(self.codeProject.generatorOptions.disabled) {
        [codeBuilder appendBlankLine];
        [codeBuilder appendPreprocessorIf:@"DISABLED"];
        [codeBuilder appendBlankLine];
	} 
}

- (void) writeCodeToHeaderFile:(FLObjcFile*) file withCodeBuilder:(FLObjcCodeBuilder*) codeBuilder {
    [self writeCodeToFile:file withCodeBuilder:codeBuilder];
}

- (void) writeCodeToSourceFile:(FLObjcFile*) file withCodeBuilder:(FLObjcCodeBuilder*) codeBuilder {
    [self writeCodeToFile:file withCodeBuilder:codeBuilder];
}



@end
