// 
// FLFacebookFriendList.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookFriendList.h"
#import "FLFacebookNamedObject.h"
#import "FLObjectDescriber.h"
@implementation FLFacebookFriendList
@synthesize friends = _friends;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"friend" propertyClass:[FLFacebookNamedObject class]] forContainerProperty:@"friends"];
}
+(FLFacebookFriendList*) facebookFriendList {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_friends release];
    [super dealloc];
}
#endif
@end
