// 
// FLFacebookNote.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookNote.h"
#import "FLFacebookNamedObject.h"
#import "FLFacebookObject.h"
@implementation FLFacebookNote
@synthesize updated_time = _updated_time;
@synthesize message = _message;
@synthesize subject = _subject;
@synthesize icon = _icon;
@synthesize created_time = _created_time;
@synthesize from = _from;
+(FLFacebookNote*) facebookNote {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_updated_time release];
    [_message release];
    [_subject release];
    [_icon release];
    [_created_time release];
    [_from release];
    [super dealloc];
}
#endif
@end
