// 
// FLFacebookObject.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookObject.h"
#import "FLModelObject.h"
@implementation FLFacebookObject
@synthesize id = _id;
+(FLFacebookObject*) facebookObject {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_id release];
    [super dealloc];
}
#endif
@end
