// 
// FLWsdlChoiceArray.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlChoiceArray.h"
#import "FLWsdlElement.h"
#import "FLObjectDescriber.h"
@implementation FLWsdlChoiceArray
@synthesize maxOccurs = _maxOccurs;
@synthesize element = _element;
@synthesize minOccurs = _minOccurs;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"element" propertyClass:[FLWsdlElement class]] forContainerProperty:@"element"];
}
+(FLWsdlChoiceArray*) wsdlChoiceArray {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_maxOccurs release];
    [_element release];
    [_minOccurs release];
    [super dealloc];
}
#endif
@end
