// 
// FLWsdlPortType.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlPortType.h"
#import "FLObjectDescriber.h"
#import "FLWsdlOperation.h"
#import "FLWsdlServiceAddress.h"
@implementation FLWsdlPortType
@synthesize operation = _operation;
@synthesize binding = _binding;
@synthesize name = _name;
@synthesize address = _address;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"operation" propertyClass:[FLWsdlOperation class]] forContainerProperty:@"operation"];
}
+(FLWsdlPortType*) wsdlPortType {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_operation release];
    [_binding release];
    [_name release];
    [_address release];
    [super dealloc];
}
#endif
@end
