// 
// FLWsdlMessage.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 4:39 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlMessage.h"
#import "FLWsdlPart.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
@implementation FLWsdlMessage
@synthesize name = _name;
@synthesize parts = _parts;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"part" propertyClass:[FLWsdlPart class]] forContainerProperty:@"parts"];
}
+(FLWsdlMessage*) wsdlMessage {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_name release];
    [_parts release];
    [super dealloc];
}
#endif
@end
