// 
// FLWsdlElement.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlElement.h"
#import "FLWsdlComplexType.h"
@implementation FLWsdlElement
@synthesize ref = _ref;
@synthesize nillable = _nillable;
@synthesize maxOccurs = _maxOccurs;
@synthesize minOccurs = _minOccurs;
@synthesize type = _type;
@synthesize complexType = _complexType;
@synthesize name = _name;
+(FLWsdlElement*) wsdlElement {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_ref release];
    [_maxOccurs release];
    [_minOccurs release];
    [_type release];
    [_complexType release];
    [_name release];
    [super dealloc];
}
#endif
@end
