// 
// FLWsdlPortType.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/29/13 1:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlPortType.h"
#import "FLWsdlOperation.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlServiceAddress.h"
@implementation FLWsdlPortType
@synthesize binding = _binding;
@synthesize operations = _operations;
@synthesize name = _name;
@synthesize address = _address;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"operation" propertyClass:[FLWsdlOperation class]] forContainerProperty:@"operations"];
}
+(FLWsdlPortType*) wsdlPortType {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_binding release];
    [_operations release];
    [_name release];
    [_address release];
    [super dealloc];
}
#endif
@end
