// 
// FLWsdlRestrictionArray.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlSequenceArray.h"
@class FLWsdlEnumeration;
@class FLObjectDescriber;
@class FLWsdlElement;
@interface FLWsdlRestrictionArray : FLWsdlSequenceArray {
@private
    NSString* _base;
    NSMutableArray* _element;
    NSMutableArray* _enumeration;
}

@property (readwrite, strong, nonatomic) NSString* base;
@property (readwrite, strong, nonatomic) NSMutableArray* element;
@property (readwrite, strong, nonatomic) NSMutableArray* enumeration;
+(FLWsdlRestrictionArray*) wsdlRestrictionArray;
@end
