// 
// FLWsdlSimpleType.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlSimpleType.h"
#import "FLWsdlRestrictionArray.h"
#import "FLWsdlList.h"
@implementation FLWsdlSimpleType
@synthesize name = _name;
@synthesize restriction = _restriction;
@synthesize list = _list;
+(FLWsdlSimpleType*) wsdlSimpleType {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_name release];
    [_restriction release];
    [_list release];
    [super dealloc];
}
#endif
@end
