// 
// FLWsdlChoiceArray.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLModelObject.h"
@class FLWsdlElement;
@class FLObjectDescriber;
@interface FLWsdlChoiceArray : FLModelObject {
@private
    NSString* _maxOccurs;
    NSMutableArray* _element;
    NSString* _minOccurs;
}

@property (readwrite, strong, nonatomic) NSString* maxOccurs;
@property (readwrite, strong, nonatomic) NSMutableArray* element;
@property (readwrite, strong, nonatomic) NSString* minOccurs;
+(FLWsdlChoiceArray*) wsdlChoiceArray;
@end
