// 
// FLWsdlBinding.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/29/13 1:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlBinding.h"
#import "FLWsdlBinding.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlOperation.h"
@implementation FLWsdlBinding
@synthesize operations = _operations;
@synthesize style = _style;
@synthesize verb = _verb;
@synthesize transport = _transport;
@synthesize type = _type;
@synthesize name = _name;
@synthesize bindings = _bindings;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"operation" propertyClass:[FLWsdlOperation class]] forContainerProperty:@"operations"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"binding" propertyClass:[FLWsdlBinding class]] forContainerProperty:@"bindings"];
}
+(FLWsdlBinding*) wsdlBinding {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_operations release];
    [_style release];
    [_verb release];
    [_transport release];
    [_type release];
    [_name release];
    [_bindings release];
    [super dealloc];
}
#endif
@end
