// 
// FLWsdlChoiceArray.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/29/13 1:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlChoiceArray.h"
#import "FLWsdlElement.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
@implementation FLWsdlChoiceArray
@synthesize maxOccurs = _maxOccurs;
@synthesize elements = _elements;
@synthesize minOccurs = _minOccurs;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"element" propertyClass:[FLWsdlElement class]] forContainerProperty:@"elements"];
}
+(FLWsdlChoiceArray*) wsdlChoiceArray {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_maxOccurs release];
    [_elements release];
    [_minOccurs release];
    [super dealloc];
}
#endif
@end
