// 
// FLWsdlImport.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLModelObject.h"
@interface FLWsdlImport : FLModelObject {
@private
    NSString* _namespace;
    NSString* _import;
}

@property (readwrite, strong, nonatomic) NSString* namespace;
@property (readwrite, strong, nonatomic) NSString* import;
+(FLWsdlImport*) wsdlImport;
@end
