// 
// FLWsdlService.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlService.h"
#import "FLObjectDescriber.h"
#import "FLWsdlPortType.h"
@implementation FLWsdlService
@synthesize name = _name;
@synthesize port = _port;
@synthesize documentation = _documentation;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"port" propertyClass:[FLWsdlPortType class]] forContainerProperty:@"port"];
}
+(FLWsdlService*) wsdlService {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_name release];
    [_port release];
    [_documentation release];
    [super dealloc];
}
#endif
@end
