// 
// FLWsdlImport.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlImport.h"
@implementation FLWsdlImport
@synthesize namespace = _namespace;
@synthesize import = _import;
+(FLWsdlImport*) wsdlImport {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_namespace release];
    [_import release];
    [super dealloc];
}
#endif
@end
