// 
// FLWsdlComplexContent.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/29/13 1:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlComplexContent.h"
#import "FLWsdlExtension.h"
#import "FLWsdlRestrictionArray.h"
#import "FLModelObject.h"
@implementation FLWsdlComplexContent
@synthesize mixed = _mixed;
@synthesize extension = _extension;
@synthesize restriction = _restriction;
+(FLWsdlComplexContent*) wsdlComplexContent {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_mixed release];
    [_extension release];
    [_restriction release];
    [super dealloc];
}
#endif
@end
