// 
// FLWsdlService.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLModelObject.h"
@class FLObjectDescriber;
@class FLWsdlPortType;
@interface FLWsdlService : FLModelObject {
@private
    NSString* _name;
    NSMutableArray* _port;
    NSString* _documentation;
}

@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) NSMutableArray* port;
@property (readwrite, strong, nonatomic) NSString* documentation;
+(FLWsdlService*) wsdlService;
@end
