// 
// FLWsdlRestrictionArray.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlRestrictionArray.h"
#import "FLWsdlEnumeration.h"
#import "FLObjectDescriber.h"
#import "FLWsdlElement.h"
@implementation FLWsdlRestrictionArray
@synthesize base = _base;
@synthesize element = _element;
@synthesize enumeration = _enumeration;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"element" propertyClass:[FLWsdlElement class]] forContainerProperty:@"element"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"enumeration" propertyClass:[FLWsdlEnumeration class]] forContainerProperty:@"enumeration"];
}
+(FLWsdlRestrictionArray*) wsdlRestrictionArray {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_base release];
    [_element release];
    [_enumeration release];
    [super dealloc];
}
#endif
@end
