// 
// FLWsdlPart.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Generated by: Mike Fullerton @ 5/14/13 1:05 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLWsdlPart.h"
@implementation FLWsdlPart
@synthesize name = _name;
@synthesize element = _element;
@synthesize type = _type;
+(FLWsdlPart*) wsdlPart {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_name release];
    [_element release];
    [_type release];
    [super dealloc];
}
#endif
@end
