// 
// ZFMovePhoto.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFMovePhoto.h"
#import "FLModelObject.h"

@implementation ZFMovePhoto

#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif
@synthesize destSetId = _destSetId;
@synthesize index = _index;
+ (ZFMovePhoto*) movePhoto {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize photoId = _photoId;
@synthesize srcSetId = _srcSetId;

@end
