// 
// ZFReorderGroup.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 12:06 PM with PackMule (3.0.0.20)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFReorderGroup.h"
#import "FLModelObject.h"
#import "ZFGroupShiftOrder.h"

@implementation ZFReorderGroup

#if FL_MRC
- (void) dealloc {
    [_shiftOrder release];
    [super dealloc];
}
#endif
@synthesize groupId = _groupId;
+ (ZFReorderGroup*) reorderGroup {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize shiftOrder = _shiftOrder;
- (ZFGroupShiftOrder) shiftOrderEnum {
    return ZFGroupShiftOrderEnumFromString(self.shiftOrder);
}
- (void) setShiftOrderEnum:(ZFGroupShiftOrder) value {
    self.shiftOrder = ZFGroupShiftOrderStringFromEnum(value);
}
- (ZFGroupShiftOrderEnumSet*) shiftOrderEnumSet {
    return [ZFGroupShiftOrderEnumSet enumSet:self.shiftOrder];;
}
- (void) setShiftOrderEnumSet:(ZFGroupShiftOrderEnumSet*) value {
    self.shiftOrder = value.concatenatedString;
}

@end
