// 
// ZFSortOrder.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLTypeSpecificEnumSet.h"

typedef enum {
    ZFSortOrderDate = 0,
    ZFSortOrderPopularity = 1,
    ZFSortOrderRank = 2,
} ZFSortOrder;

#define kZFSortOrderRank @"Rank"
#define kZFSortOrderDate @"Date"
#define kZFSortOrderPopularity @"Popularity"

extern NSString* ZFSortOrderStringFromEnum(ZFSortOrder theEnum);
extern ZFSortOrder ZFSortOrderEnumFromString(NSString* theString);

@interface ZFSortOrderEnumSet : FLTypeSpecificEnumSet
+ (id) enumSet;
+ (id) enumSet:(NSString*) concatenatedEnumString;
@end
