// 
// FLMyEnum.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp
// Schema: FLTestObjects
// 
// Generated by: Mike Fullerton @ 5/21/13 9:17 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC (http://www.greentongue.com)
// 
// License: Individual licensees only.
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
typedef enum {
    FLMyEnumFoobar,
    FLMyEnumBar,
    FLMyEnumFoo,
} FLMyEnum;
