// 
// FLTestObject.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp
// Schema: FLTestObjects
// 
// Generated by: Mike Fullerton @ 5/21/13 9:17 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC (http://www.greentongue.com)
// 
// License: Individual licensees only.
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLTestObject.h"
#import "FLXmlParser.h"
#import "FLObjectDescriber.h"
#import "FLGuid.h"
#import "FLMyEnum.h"
@implementation FLTestObject
@synthesize bob = _bob;
@synthesize databaseGuid = _databaseGuid;
@synthesize foo = _foo;
@synthesize rambo = _rambo;
@synthesize anotherInt = _anotherInt;
@synthesize testFloat = _testFloat;
@synthesize rect = _rect;
@synthesize stateEnum = _stateEnum;
@synthesize point = _point;
@synthesize foop = _foop;
@synthesize dateCreated = _dateCreated;
@synthesize chloe = _chloe;
@synthesize size = _size;
@synthesize myBool = _myBool;
@synthesize sanjo = _sanjo;
@synthesize dateModified = _dateModified;
@synthesize testInt = _testInt;
@synthesize myString = _myString;
@synthesize expireDate = _expireDate;
@synthesize anArray = _anArray;
@synthesize teddy = _teddy;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"parser" propertyClass:[FLXmlParser class]] forContainerProperty:@"anArray"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"number" propertyClass:[NSNumber class]] forContainerProperty:@"anArray"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"item" propertyClass:[NSString class]] forContainerProperty:@"anArray"];
}
+(FLTestObject*) testObject {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_bob release];
    [_databaseGuid release];
    [_foo release];
    [_rambo release];
    [_foopy release];
    [_iLikeRum release];
    [_foop release];
    [_dateCreated release];
    [_chloe release];
    [_sanjo release];
    [_dateModified release];
    [_myString release];
    [_expireDate release];
    [_anArray release];
    [_teddy release];
    [super dealloc];
}
#endif
@end
