// 
// FLFacebookComment.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookObject.h"
@class FLFacebookNamedObject;
@interface FLFacebookComment : FLFacebookObject {
@private
    NSString* _message;
    int _likes;
    NSDate* _created_time;
    FLFacebookNamedObject* _from;
}

@property (readwrite, strong, nonatomic) NSString* message;
@property (readwrite, assign, nonatomic) int likes;
@property (readwrite, strong, nonatomic) NSDate* created_time;
@property (readwrite, strong, nonatomic) FLFacebookNamedObject* from;
+(FLFacebookComment*) facebookComment;
@end
