// 
// FLParseCredentials.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: Narcissist
// Schema: ParseCredentials
// 
// Generated by: Mike Fullerton @ 5/25/13 10:00 AM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software LLC, Mike Fullerton
// 
// License: The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 
// Copywrite (C) 2013 GreenTongue Software LLC, Mike Fullerton. All rights reserved.
// 
#import "FLModelObject.h"
@interface FLParseCredentials : FLModelObject {
@private
    NSString* _password;
    NSString* _username;
    NSString* _masterKey;
    NSString* _clientKey;
    NSString* _applicationID;
}

@property (readwrite, strong, nonatomic) NSString* password;
@property (readwrite, strong, nonatomic) NSString* username;
@property (readwrite, strong, nonatomic) NSString* masterKey;
@property (readwrite, strong, nonatomic) NSString* clientKey;
@property (readwrite, strong, nonatomic) NSString* applicationID;
+(FLParseCredentials*) parseCredentials;
@end
