// 
// ZFSearchSetByText.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 12:06 PM with PackMule (3.0.0.20)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "FLModelObject.h"
#import "ZFSearchSetByText.h"
#import "ZFSortOrder.h"
#import "ZFPhotoSetType.h"

@implementation ZFSearchSetByText

#if FL_MRC
- (void) dealloc {
    [_query release];
    [_type release];
    [_searchId release];
    [_sortOrder release];
    [super dealloc];
}
#endif
@synthesize limit = _limit;
@synthesize offset = _offset;
@synthesize query = _query;
@synthesize searchId = _searchId;
+ (ZFSearchSetByText*) searchSetByText {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize sortOrder = _sortOrder;
- (ZFSortOrder) sortOrderEnum {
    return ZFSortOrderEnumFromString(self.sortOrder);
}
- (void) setSortOrderEnum:(ZFSortOrder) value {
    self.sortOrder = ZFSortOrderStringFromEnum(value);
}
- (ZFSortOrderEnumSet*) sortOrderEnumSet {
    return [ZFSortOrderEnumSet enumSet:self.sortOrder];;
}
- (void) setSortOrderEnumSet:(ZFSortOrderEnumSet*) value {
    self.sortOrder = value.concatenatedString;
}
@synthesize type = _type;
- (ZFPhotoSetType) typeEnum {
    return ZFPhotoSetTypeEnumFromString(self.type);
}
- (void) setTypeEnum:(ZFPhotoSetType) value {
    self.type = ZFPhotoSetTypeStringFromEnum(value);
}
- (ZFPhotoSetTypeEnumSet*) typeEnumSet {
    return [ZFPhotoSetTypeEnumSet enumSet:self.type];;
}
- (void) setTypeEnumSet:(ZFPhotoSetTypeEnumSet*) value {
    self.type = value.concatenatedString;
}

@end
