// 
// FLFacebookStatusMessage.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLFacebookStatusMessage.h"
#import "FLFacebookNamedObject.h"
@implementation FLFacebookStatusMessage
@synthesize message = _message;
@synthesize updated_time = _updated_time;
@synthesize from = _from;
+(FLFacebookStatusMessage) statusMessage {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_message release];
    [_updated_time release];
    [_from release];
    [super dealloc];
}
#endif
@end
