// 
// FLFacebookPhoto.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLFacebookPhoto.h"
#import "FLFacebookNamedObject.h"
@implementation FLFacebookPhoto
@synthesize from = _from;
@synthesize source = _source;
@synthesize height = _height;
@synthesize tags = _tags;
@synthesize updated_time = _updated_time;
@synthesize width = _width;
@synthesize link = _link;
@synthesize icon = _icon;
@synthesize created_time = _created_time;
+(FLFacebookPhoto) photo {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_from release];
    [_source release];
    [_tags release];
    [_updated_time release];
    [_link release];
    [_icon release];
    [_created_time release];
    [super dealloc];
}
#endif
@end
