// 
// FLFacebookApplication.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLFacebookApplication.h"
@implementation FLFacebookApplication
@synthesize link = _link;
@synthesize category = _category;
@synthesize description = _description;
+(FLFacebookApplication) application {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_link release];
    [_category release];
    [_description release];
    [super dealloc];
}
#endif
@end
