// 
// FLFacebookMessage.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. 
//  The FishLamp Framework is released under the MIT License: http://fishlamp.com/license 
// 
#import "FLModelObject.h"
@class FLFacebookEmailObject
@interface FLFacebookMessage : FLModelObject {
@private
    NSString* _message;
    FLFacebookEmailObject* _to;
    NSDate* _created_time;
    FLFacebookEmailObject* _from;
}

@property (readwrite, strong, nonatomic) NSString* message;
@property (readwrite, strong, nonatomic) FLFacebookEmailObject* to;
@property (readwrite, strong, nonatomic) NSDate* created_time;
@property (readwrite, strong, nonatomic) FLFacebookEmailObject* from;
+(FLFacebookMessage) message;
@end
