// 
// FLFacebookTag.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. 
//  The FishLamp Framework is released under the MIT License: http://fishlamp.com/license 
// 
#import "FLModelObject.h"
@class FLFacebookNamedObject
@interface FLFacebookTag : FLModelObject {
@private
    int _x;
    FLFacebookNamedObject* _user;
    int _y;
}

@property (readwrite, assign, nonatomic) int x;
@property (readwrite, strong, nonatomic) FLFacebookNamedObject* user;
@property (readwrite, assign, nonatomic) int y;
+(FLFacebookTag) tag;
@end
