// 
// FLFacebookGroup.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLFacebookGroup.h"
@implementation FLFacebookGroup
@synthesize updated_time = _updated_time;
@synthesize owner = _owner;
@synthesize icon = _icon;
@synthesize description = _description;
@synthesize privacy = _privacy;
@synthesize link = _link;
+(FLFacebookGroup) group {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_updated_time release];
    [_owner release];
    [_icon release];
    [_description release];
    [_privacy release];
    [_link release];
    [super dealloc];
}
#endif
@end
