// 
// ZFGetRecentSets.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "ZFPhotoSetType.h"

@class ZFPhotoSetTypeEnumSet;

@interface ZFGetRecentSets : FLModelObject {
@private
    NSString* _type;
    int _limit;
    int _offset;
}

@property (readwrite, assign, nonatomic) int limit;
@property (readwrite, assign, nonatomic) int offset;
@property (readwrite, strong, nonatomic) NSString* type;
@property (readwrite, assign, nonatomic) ZFPhotoSetType typeEnum;
@property (readwrite, strong, nonatomic) ZFPhotoSetTypeEnumSet* typeEnumSet;

+ (ZFGetRecentSets*) getRecentSets;

@end
