// 
// ZFLoadMessagesResponse.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFLoadMessagesResponse.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "ZFMessage.h"

@implementation ZFLoadMessagesResponse

#if FL_MRC
- (void) dealloc {
    [_loadMessagesResult release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"Message" propertyClass:[ZFMessage class]] forContainerProperty:@"loadMessagesResult"];
}
+ (ZFLoadMessagesResponse*) loadMessagesResponse {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize loadMessagesResult = _loadMessagesResult;

@end
