// 
// ZFPhoto.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "ZFPhotoFlags.h"
#import "ZFPhotoRotation.h"

@class ZFExifTag;
@class ZFPhotoRotationEnumSet;
@class FLObjectDescriber;
@class ZFAccessDescriptor;
@class ZFPhotoFlagsEnumSet;

@interface ZFPhoto : FLModelObject {
@private
    NSString* _rotation;
    NSString* _title;
    NSString* _urlCore;
    int _duration;
    NSString* _mimeType;
    NSString* _originalUrl;
    NSString* _owner;
    ZFAccessDescriptor* _accessDescriptor;
    NSString* _mailboxId;
    int _views;
    NSMutableArray* _keywords;
    NSString* _urlToken;
    NSString* _pageUrl;
    NSMutableArray* _exifTags;
    int _size;
    NSString* _flags;
    NSDate* _takenOn;
    long _id;
    NSString* _caption;
    NSString* _fileName;
    long _pricingKey;
    int _textCn;
    unsigned int _height;
    unsigned int _width;
    NSString* _urlHost;
    NSDate* _uploadedOn;
    BOOL _isVideo;
    long _gallery;
    NSString* _sequence;
    NSString* _copyright;
    NSMutableArray* _categories;
    NSString* _shortExif;
}

@property (readwrite, strong, nonatomic) ZFAccessDescriptor* accessDescriptor;
@property (readwrite, strong, nonatomic) NSString* caption;
@property (readwrite, strong, nonatomic) NSMutableArray* categories;
@property (readwrite, strong, nonatomic) NSString* copyright;
@property (readwrite, assign, nonatomic) int duration;
@property (readwrite, strong, nonatomic) NSMutableArray* exifTags;
@property (readwrite, strong, nonatomic) NSString* fileName;
@property (readwrite, strong, nonatomic) NSString* flags;
@property (readwrite, assign, nonatomic) ZFPhotoFlags flagsEnum;
@property (readwrite, strong, nonatomic) ZFPhotoFlagsEnumSet* flagsEnumSet;
@property (readwrite, assign, nonatomic) long gallery;
@property (readwrite, assign, nonatomic) unsigned int height;
@property (readwrite, assign, nonatomic) long id;
@property (readwrite, assign, nonatomic) BOOL isVideo;
@property (readwrite, strong, nonatomic) NSMutableArray* keywords;
@property (readwrite, strong, nonatomic) NSString* mailboxId;
@property (readwrite, strong, nonatomic) NSString* mimeType;
@property (readwrite, strong, nonatomic) NSString* originalUrl;
@property (readwrite, strong, nonatomic) NSString* owner;
@property (readwrite, strong, nonatomic) NSString* pageUrl;
@property (readwrite, assign, nonatomic) long pricingKey;
@property (readwrite, strong, nonatomic) NSString* rotation;
@property (readwrite, assign, nonatomic) ZFPhotoRotation rotationEnum;
@property (readwrite, strong, nonatomic) ZFPhotoRotationEnumSet* rotationEnumSet;
@property (readwrite, strong, nonatomic) NSString* sequence;
@property (readwrite, strong, nonatomic) NSString* shortExif;
@property (readwrite, assign, nonatomic) int size;
@property (readwrite, strong, nonatomic) NSDate* takenOn;
@property (readwrite, assign, nonatomic) int textCn;
@property (readwrite, strong, nonatomic) NSString* title;
@property (readwrite, strong, nonatomic) NSDate* uploadedOn;
@property (readwrite, strong, nonatomic) NSString* urlCore;
@property (readwrite, strong, nonatomic) NSString* urlHost;
@property (readwrite, strong, nonatomic) NSString* urlToken;
@property (readwrite, assign, nonatomic) int views;
@property (readwrite, assign, nonatomic) unsigned int width;

+ (ZFPhoto*) photo;

@end
