// 
// ZFSearchPhotoByCategoryHttpPostIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFSearchPhotoByCategoryHttpPostIn.h"
#import "FLModelObject.h"

@implementation ZFSearchPhotoByCategoryHttpPostIn

@synthesize categoryCode = _categoryCode;
#if FL_MRC
- (void) dealloc {
    [_limit release];
    [_offset release];
    [_searchId release];
    [_sortOrder release];
    [_categoryCode release];
    [super dealloc];
}
#endif
@synthesize limit = _limit;
@synthesize offset = _offset;
@synthesize searchId = _searchId;
+ (ZFSearchPhotoByCategoryHttpPostIn*) searchPhotoByCategoryHttpPostIn {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize sortOrder = _sortOrder;

@end
