// 
// FLFacebookLoadUserPictureOperationInput.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookLoadUserPictureOperationInput.h"
#import "FLModelObject.h"
@implementation FLFacebookLoadUserPictureOperationInput
@synthesize type = _type;
@synthesize pictureSize = _pictureSize;
+(FLFacebookLoadUserPictureOperationInput*) facebookLoadUserPictureOperationInput {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_type release];
    [_pictureSize release];
    [super dealloc];
}
#endif
@end
