// 
// ZFDeleteGroupHttpGetIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "FLModelObject.h"
#import "ZFDeleteGroupHttpGetIn.h"

@implementation ZFDeleteGroupHttpGetIn

#if FL_MRC
- (void) dealloc {
    [_groupId release];
    [super dealloc];
}
#endif
+ (ZFDeleteGroupHttpGetIn*) deleteGroupHttpGetIn {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize groupId = _groupId;

@end
