// 
// ZFLoadPhotoSetHttpPostIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "FLModelObject.h"
#import "ZFLoadPhotoSetHttpPostIn.h"

@implementation ZFLoadPhotoSetHttpPostIn

#if FL_MRC
- (void) dealloc {
    [_level release];
    [_photoSetId release];
    [_includePhotos release];
    [super dealloc];
}
#endif
@synthesize includePhotos = _includePhotos;
@synthesize level = _level;
+ (ZFLoadPhotoSetHttpPostIn*) loadPhotoSetHttpPostIn {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize photoSetId = _photoSetId;

@end
