// 
// ZFMessageUpdater.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"


@interface ZFMessageUpdater : FLModelObject {
@private
    NSString* _posterName;
    NSString* _body;
    BOOL _isPrivate;
    NSString* _posterUrl;
    NSString* _posterEmail;
}

@property (readwrite, strong, nonatomic) NSString* body;
@property (readwrite, assign, nonatomic) BOOL isPrivate;
@property (readwrite, strong, nonatomic) NSString* posterEmail;
@property (readwrite, strong, nonatomic) NSString* posterName;
@property (readwrite, strong, nonatomic) NSString* posterUrl;

+ (ZFMessageUpdater*) messageUpdater;

@end
