// 
// ZFReindexPhotoSetHttpGetIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFReindexPhotoSetHttpGetIn.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"

@implementation ZFReindexPhotoSetHttpGetIn

#if FL_MRC
- (void) dealloc {
    [_mapping release];
    [_photoSetId release];
    [_startIndex release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"String" propertyClass:[NSString class]] forContainerProperty:@"mapping"];
}
@synthesize mapping = _mapping;
@synthesize photoSetId = _photoSetId;
+ (ZFReindexPhotoSetHttpGetIn*) reindexPhotoSetHttpGetIn {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize startIndex = _startIndex;

@end
