// 
// ZFSearchPhotoByCategoryResponse.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFPhotoResult.h"
#import "ZFSearchPhotoByCategoryResponse.h"
#import "FLModelObject.h"

@implementation ZFSearchPhotoByCategoryResponse

#if FL_MRC
- (void) dealloc {
    [_searchPhotoByCategoryResult release];
    [super dealloc];
}
#endif
+ (ZFSearchPhotoByCategoryResponse*) searchPhotoByCategoryResponse {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize searchPhotoByCategoryResult = _searchPhotoByCategoryResult;

@end
