// 
// ZFUser.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFGroup.h"
#import "ZFAddress.h"
#import "ZFPhotoSet.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "ZFUser.h"
#import "ZFFile.h"

@implementation ZFUser

@synthesize balance = _balance;
@synthesize bio = _bio;
@synthesize bioPhoto = _bioPhoto;
@synthesize collectionCount = _collectionCount;
#if FL_MRC
- (void) dealloc {
    [_lastName release];
    [_personalAddress release];
    [_bioPhoto release];
    [_firstName release];
    [_loginName release];
    [_featuredPhotoSets release];
    [_recentPhotoSets release];
    [_displayName release];
    [_bio release];
    [_lastUpdated release];
    [_referralCode release];
    [_domainName release];
    [_rootGroup release];
    [_userSince release];
    [_publicAddress release];
    [_expiresOn release];
    [_primaryEmail release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"PhotoSet" propertyClass:[ZFPhotoSet class]] forContainerProperty:@"featuredPhotoSets"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"PhotoSet" propertyClass:[ZFPhotoSet class]] forContainerProperty:@"recentPhotoSets"];
}
@synthesize displayName = _displayName;
@synthesize domainName = _domainName;
@synthesize expiresOn = _expiresOn;
@synthesize featuredPhotoSets = _featuredPhotoSets;
@synthesize firstName = _firstName;
@synthesize galleryCount = _galleryCount;
@synthesize hierarchyCn = _hierarchyCn;
@synthesize lastName = _lastName;
@synthesize lastUpdated = _lastUpdated;
@synthesize loginName = _loginName;
@synthesize personalAddress = _personalAddress;
@synthesize photoBytes = _photoBytes;
@synthesize photoBytesQuota = _photoBytesQuota;
@synthesize photoCount = _photoCount;
@synthesize primaryEmail = _primaryEmail;
@synthesize publicAddress = _publicAddress;
@synthesize recentPhotoSets = _recentPhotoSets;
@synthesize referralCode = _referralCode;
@synthesize rootGroup = _rootGroup;
@synthesize storageQuota = _storageQuota;
+ (ZFUser*) user {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize userSince = _userSince;
@synthesize videoBytesQuota = _videoBytesQuota;
@synthesize videoDurationQuota = _videoDurationQuota;
@synthesize views = _views;

@end
