// 
// FLFacebookGroup.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookNamedObject.h"
@interface FLFacebookGroup : FLFacebookNamedObject {
@private
    NSDate* _updated_time;
    NSString* _owner;
    NSString* _icon;
    NSString* _description;
    NSString* _privacy;
    NSString* _link;
}

@property (readwrite, strong, nonatomic) NSDate* updated_time;
@property (readwrite, strong, nonatomic) NSString* owner;
@property (readwrite, strong, nonatomic) NSString* icon;
@property (readwrite, strong, nonatomic) NSString* description;
@property (readwrite, strong, nonatomic) NSString* privacy;
@property (readwrite, strong, nonatomic) NSString* link;
+(FLFacebookGroup*) facebookGroup;
@end
