// 
// ZFAccessUpdater.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "ZFApiAccessMask.h"
@class ZFApiAccessMaskEnumSet;
#import "ZFAccessType.h"
@class ZFAccessTypeEnumSet;
@class FLObjectDescriber;
#import "ZFApiAccessMask.h"
#import "ZFAccessType.h"
@interface ZFAccessUpdater : FLModelObject {
@private
    NSString* _password;
    NSString* _passwordHint;
    NSString* _accessMask;
    NSString* _accessType;
    BOOL _isDerived;
    NSMutableArray* _viewers;
}

@property (readwrite, strong, nonatomic) ZFAccessTypeEnumSet* accessTypeEnumSet;
@property (readwrite, strong, nonatomic) NSString* password;
@property (readwrite, assign, nonatomic) ZFApiAccessMask accessMaskEnum;
@property (readwrite, strong, nonatomic) ZFApiAccessMaskEnumSet* accessMaskEnumSet;
@property (readwrite, assign, nonatomic) BOOL isDerived;
@property (readwrite, assign, nonatomic) NSString* accessMask;
@property (readwrite, assign, nonatomic) ZFAccessType accessTypeEnum;
@property (readwrite, strong, nonatomic) NSMutableArray* viewers;
@property (readwrite, strong, nonatomic) NSString* passwordHint;
@property (readwrite, assign, nonatomic) NSString* accessType;
+ (ZFAccessUpdater*) accessUpdater;
@end
