// 
// ZFApiHttpPostCreateFavoritesSet.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "FLHttpRequestDescriptor.h"

@class ZFCreateFavoritesSetHttpPostIn;

@interface ZFApiHttpPostCreateFavoritesSet : FLModelObject<FLHttpRequestDescriptor> {
@private
    ZFCreateFavoritesSetHttpPostIn* _input;
    long _output;
}

@property (readwrite, strong, nonatomic) ZFCreateFavoritesSetHttpPostIn* input;
@property (readonly, strong, nonatomic) NSString* location;
@property (readonly, strong, nonatomic) NSString* operationName;
@property (readwrite, assign, nonatomic) long output;
@property (readonly, strong, nonatomic) NSString* targetNamespace;

+ (ZFApiHttpPostCreateFavoritesSet*) apiHttpPostCreateFavoritesSet;

@end
