// 
// ZFApiHttpGetRotatePhoto.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@class ZFPhoto;
#import "FLHttpRequestDescriptor.h"
@class ZFRotatePhotoHttpGetIn;
@interface ZFApiHttpGetRotatePhoto : FLModelObject<FLHttpRequestDescriptor> {
@private
    ZFRotatePhotoHttpGetIn* _input;
    ZFPhoto* _output;
}

@property (readonly, strong, nonatomic) NSString* targetNamespace;
@property (readwrite, strong, nonatomic) ZFRotatePhotoHttpGetIn* input;
@property (readwrite, strong, nonatomic) ZFPhoto* output;
@property (readonly, strong, nonatomic) NSString* location;
@property (readonly, strong, nonatomic) NSString* operationName;
+ (ZFApiHttpGetRotatePhoto*) apiHttpGetRotatePhoto;
@end
