// 
// ZFApiHttpPostSearchPhotoByCategory.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "FLHttpRequestDescriptor.h"

@class ZFSearchPhotoByCategoryHttpPostIn;
@class ZFPhotoResult;

@interface ZFApiHttpPostSearchPhotoByCategory : FLModelObject<FLHttpRequestDescriptor> {
@private
    ZFSearchPhotoByCategoryHttpPostIn* _input;
    ZFPhotoResult* _output;
}

@property (readwrite, strong, nonatomic) ZFSearchPhotoByCategoryHttpPostIn* input;
@property (readonly, strong, nonatomic) NSString* location;
@property (readonly, strong, nonatomic) NSString* operationName;
@property (readwrite, strong, nonatomic) ZFPhotoResult* output;
@property (readonly, strong, nonatomic) NSString* targetNamespace;

+ (ZFApiHttpPostSearchPhotoByCategory*) apiHttpPostSearchPhotoByCategory;

@end
