// 
// ZFApiSoap.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 2:36 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@class ZFApiSoapLoadGroupHierarchy;
@class ZFApiSoapUndeleteMessage;
@class ZFApiSoapUpdatePhotoSet;
@class ZFApiSoapCreatePhotoFromUrl;
@class ZFApiSoapSearchSetByText;
@class ZFApiSoapKeyringGetUnlockedRealms;
@class ZFApiSoapLoadSharedFavoritesSets;
@class ZFApiSoapLoadPhotoSet;
@class ZFApiSoapLoadPrivateProfile;
@class ZFApiSoapSetGroupTitlePhoto;
@class ZFApiSoapMovePhotos;
@class ZFApiSoapCreateQuickBlogPost;
@class ZFApiSoapRemoveGroupTitlePhoto;
@class ZFApiSoapCheckPrivilege;
@class ZFApiSoapCreatePhotoSet;
@class ZFApiSoapReindexPhotoSet;
@class ZFApiSoapSetPhotoSetFeaturedIndex;
@class ZFApiSoapSearchSetByCategory;
@class ZFApiSoapDeletePhotos;
@class ZFApiSoapGetRecentSets;
@class ZFApiSoapDeleteMessage;
@class ZFApiSoapSetRandomPhotoSetTitlePhoto;
@class ZFApiSoapDeleteGroup;
@class ZFApiSoapUpdateGroupAccess;
@class ZFApiSoapGetVersion;
@class ZFApiSoapUpdateGroup;
@class ZFApiSoapCollectionRemovePhoto;
@class ZFApiSoapLoadPublicProfile;
@class ZFApiSoapShareFavoritesSet;
@class ZFApiSoapGetDownloadOriginalKey;
@class ZFApiSoapGetPopularPhotos;
@class ZFApiSoapAuthenticatePlain;
@class ZFApiSoapSearchPhotoByText;
@class ZFApiSoapReplacePhoto;
@class ZFApiSoapSearchPhotoByCategory;
@class ZFApiSoapDeletePhoto;
@class ZFApiSoapGetRecentPhotos;
@class ZFApiSoapCreateFavoritesSet;
@class ZFApiSoapMovePhotoSet;
@class ZFApiSoapReorderGroup;
@class ZFApiSoapUpdatePhoto;
@class ZFApiSoapRemovePhotoSetTitlePhoto;
@class ZFApiSoapLoadMessages;
@class ZFApiSoapMovePhoto;
@class ZFApiSoapDeletePhotoSet;
@class ZFApiSoapReorderPhotoSet;
@class ZFApiSoapGetVideoPlaybackUrl;
@class ZFApiSoapGetPopularSets;
@class ZFApiSoapCreateGroup;
@class ZFApiSoapCreateVideoFromUrl;
@class ZFApiSoapUpdatePhotoSetAccess;
@class ZFApiSoapMoveGroup;
@class ZFApiSoapGetCategories;
@class ZFApiSoapGetChallenge;
@class ZFApiSoapLoadPhotoSetPhotos;
@class ZFApiSoapLoadPhoto;
@class ZFApiSoapResolveReference;
@class ZFApiSoapLoadAccessRealm;
@class ZFApiSoapKeyringAddKeyPlain;
@class ZFApiSoapRotatePhoto;
@class ZFApiSoapAddMessage;
@class ZFApiSoapCollectionAddPhoto;
@class ZFApiSoapGetVisitorKey;
@class ZFApiSoapUpdatePhotoAccess;
@class ZFApiSoapAuthenticateVisitor;
@class ZFApiSoapLoadGroup;
@class ZFApiSoapSetPhotoSetTitlePhoto;
@class ZFApiSoapAuthenticate;
@interface ZFApiSoap : FLModelObject {
@private
}

@property (readonly, strong, nonatomic) NSString* url;
@property (readonly, strong, nonatomic) NSString* targetNamespace;
-(ZFApiSoapRemoveGroupTitlePhoto*) createRemoveGroupTitlePhoto;
-(ZFApiSoapRemovePhotoSetTitlePhoto*) createRemovePhotoSetTitlePhoto;
-(ZFApiSoapSetRandomPhotoSetTitlePhoto*) createSetRandomPhotoSetTitlePhoto;
-(ZFApiSoapMovePhotos*) createMovePhotos;
-(ZFApiSoapDeletePhotos*) createDeletePhotos;
-(ZFApiSoapAuthenticateVisitor*) createAuthenticateVisitor;
-(ZFApiSoapGetVisitorKey*) createGetVisitorKey;
-(ZFApiSoapAuthenticatePlain*) createAuthenticatePlain;
-(ZFApiSoapGetChallenge*) createGetChallenge;
-(ZFApiSoapAuthenticate*) createAuthenticate;
-(ZFApiSoapLoadPrivateProfile*) createLoadPrivateProfile;
-(ZFApiSoapLoadPublicProfile*) createLoadPublicProfile;
-(ZFApiSoapLoadGroupHierarchy*) createLoadGroupHierarchy;
-(ZFApiSoapLoadGroup*) createLoadGroup;
-(ZFApiSoapLoadAccessRealm*) createLoadAccessRealm;
-(ZFApiSoapLoadPhotoSet*) createLoadPhotoSet;
-(ZFApiSoapLoadPhotoSetPhotos*) createLoadPhotoSetPhotos;
-(ZFApiSoapLoadPhoto*) createLoadPhoto;
-(ZFApiSoapKeyringAddKeyPlain*) createKeyringAddKeyPlain;
-(ZFApiSoapKeyringGetUnlockedRealms*) createKeyringGetUnlockedRealms;
-(ZFApiSoapGetDownloadOriginalKey*) createGetDownloadOriginalKey;
-(ZFApiSoapGetCategories*) createGetCategories;
-(ZFApiSoapSearchSetByCategory*) createSearchSetByCategory;
-(ZFApiSoapSearchSetByText*) createSearchSetByText;
-(ZFApiSoapGetPopularSets*) createGetPopularSets;
-(ZFApiSoapGetRecentSets*) createGetRecentSets;
-(ZFApiSoapSearchPhotoByCategory*) createSearchPhotoByCategory;
-(ZFApiSoapSearchPhotoByText*) createSearchPhotoByText;
-(ZFApiSoapGetPopularPhotos*) createGetPopularPhotos;
-(ZFApiSoapGetRecentPhotos*) createGetRecentPhotos;
-(ZFApiSoapCreateGroup*) createCreateGroup;
-(ZFApiSoapDeleteGroup*) createDeleteGroup;
-(ZFApiSoapUpdateGroup*) createUpdateGroup;
-(ZFApiSoapCreatePhotoSet*) createCreatePhotoSet;
-(ZFApiSoapDeletePhotoSet*) createDeletePhotoSet;
-(ZFApiSoapUpdatePhotoSet*) createUpdatePhotoSet;
-(ZFApiSoapDeletePhoto*) createDeletePhoto;
-(ZFApiSoapUpdatePhoto*) createUpdatePhoto;
-(ZFApiSoapCollectionAddPhoto*) createCollectionAddPhoto;
-(ZFApiSoapCollectionRemovePhoto*) createCollectionRemovePhoto;
-(ZFApiSoapUpdatePhotoAccess*) createUpdatePhotoAccess;
-(ZFApiSoapUpdatePhotoSetAccess*) createUpdatePhotoSetAccess;
-(ZFApiSoapUpdateGroupAccess*) createUpdateGroupAccess;
-(ZFApiSoapReorderPhotoSet*) createReorderPhotoSet;
-(ZFApiSoapReindexPhotoSet*) createReindexPhotoSet;
-(ZFApiSoapMovePhoto*) createMovePhoto;
-(ZFApiSoapRotatePhoto*) createRotatePhoto;
-(ZFApiSoapSetGroupTitlePhoto*) createSetGroupTitlePhoto;
-(ZFApiSoapSetPhotoSetTitlePhoto*) createSetPhotoSetTitlePhoto;
-(ZFApiSoapSetPhotoSetFeaturedIndex*) createSetPhotoSetFeaturedIndex;
-(ZFApiSoapMovePhotoSet*) createMovePhotoSet;
-(ZFApiSoapReorderGroup*) createReorderGroup;
-(ZFApiSoapReplacePhoto*) createReplacePhoto;
-(ZFApiSoapMoveGroup*) createMoveGroup;
-(ZFApiSoapLoadMessages*) createLoadMessages;
-(ZFApiSoapAddMessage*) createAddMessage;
-(ZFApiSoapDeleteMessage*) createDeleteMessage;
-(ZFApiSoapUndeleteMessage*) createUndeleteMessage;
-(ZFApiSoapGetVersion*) createGetVersion;
-(ZFApiSoapCheckPrivilege*) createCheckPrivilege;
-(ZFApiSoapCreateFavoritesSet*) createCreateFavoritesSet;
-(ZFApiSoapShareFavoritesSet*) createShareFavoritesSet;
-(ZFApiSoapLoadSharedFavoritesSets*) createLoadSharedFavoritesSets;
-(ZFApiSoapGetVideoPlaybackUrl*) createGetVideoPlaybackUrl;
-(ZFApiSoapResolveReference*) createResolveReference;
-(ZFApiSoapCreateQuickBlogPost*) createCreateQuickBlogPost;
-(ZFApiSoapCreatePhotoFromUrl*) createCreatePhotoFromUrl;
-(ZFApiSoapCreateVideoFromUrl*) createCreateVideoFromUrl;
+(ZFApiSoap*) apiSoap;
@end
