// 
// ZFApi.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFApiHttpPost.h"
#import "ZFApi.h"
#import "ZFApiHttpGet.h"
#import "FLModelObject.h"
#import "ZFApiSoap.h"

@implementation ZFApi

+ (ZFApi*) api {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif
- (ZFApiHttpGet*) httpGet {
    return FLAutorelease([[ZFApiHttpGet alloc] init]);
}
- (ZFApiHttpPost*) httpPost {
    return FLAutorelease([[ZFApiHttpPost alloc] init]);
}
- (ZFApiSoap*) soap {
    return FLAutorelease([[ZFApiSoap alloc] init]);
}

@end
