// 
// ZFApiSoapRotatePhoto.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 6:24 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@class ZFRotatePhoto;
#import "FLHttpRequestDescriptor.h"
@class ZFRotatePhotoResponse;
@interface ZFApiSoapRotatePhoto : FLModelObject<FLHttpRequestDescriptor> {
@private
    ZFRotatePhoto* _input;
    ZFRotatePhotoResponse* _output;
}

@property (readwrite, strong, nonatomic) ZFRotatePhotoResponse* output;
@property (readonly, strong, nonatomic) NSString* targetNamespace;
@property (readwrite, strong, nonatomic) ZFRotatePhoto* input;
@property (readonly, strong, nonatomic) NSString* soapAction;
@property (readonly, strong, nonatomic) NSString* location;
@property (readonly, strong, nonatomic) NSString* operationName;
+ (ZFApiSoapRotatePhoto*) apiSoapRotatePhoto;
@end
