// 
// ZFApiSoapCreateFavoritesSet.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@class ZFCreateFavoritesSet;
#import "FLHttpRequestDescriptor.h"
@class ZFCreateFavoritesSetResponse;
@interface ZFApiSoapCreateFavoritesSet : FLModelObject<FLHttpRequestDescriptor> {
@private
    ZFCreateFavoritesSet* _input;
    ZFCreateFavoritesSetResponse* _output;
}

@property (readwrite, strong, nonatomic) ZFCreateFavoritesSetResponse* output;
@property (readonly, strong, nonatomic) NSString* targetNamespace;
@property (readwrite, strong, nonatomic) ZFCreateFavoritesSet* input;
@property (readonly, strong, nonatomic) NSString* soapAction;
@property (readonly, strong, nonatomic) NSString* location;
@property (readonly, strong, nonatomic) NSString* operationName;
+ (ZFApiSoapCreateFavoritesSet*) apiSoapCreateFavoritesSet;
@end
