// 
// ZFApiSoapGetChallenge.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "FLHttpRequestDescriptor.h"

@class ZFGetChallenge;
@class ZFGetChallengeResponse;

@interface ZFApiSoapGetChallenge : FLModelObject<FLHttpRequestDescriptor> {
@private
    ZFGetChallenge* _input;
    ZFGetChallengeResponse* _output;
}

@property (readwrite, strong, nonatomic) ZFGetChallenge* input;
@property (readonly, strong, nonatomic) NSString* location;
@property (readonly, strong, nonatomic) NSString* operationName;
@property (readwrite, strong, nonatomic) ZFGetChallengeResponse* output;
@property (readonly, strong, nonatomic) NSString* soapAction;
@property (readonly, strong, nonatomic) NSString* targetNamespace;

+ (ZFApiSoapGetChallenge*) apiSoapGetChallenge;

@end
