// 
// ZFApiHttpPost.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@class ZFApiHttpPostLoadSharedFavoritesSets;
@class ZFApiHttpPostRotatePhoto;
@class ZFApiHttpPostUndeleteMessage;
@class ZFApiHttpPostSearchPhotoByCategory;
@class ZFApiHttpPostMovePhoto;
@class ZFApiHttpPostSearchSetByCategory;
@class ZFApiHttpPostGetVideoPlaybackUrl;
@class ZFApiHttpPostKeyringGetUnlockedRealms;
@class ZFApiHttpPostSetRandomPhotoSetTitlePhoto;
@class ZFApiHttpPostCollectionAddPhoto;
@class ZFApiHttpPostGetVersion;
@class ZFApiHttpPostGetVisitorKey;
@class ZFApiHttpPostDeleteGroup;
@class ZFApiHttpPostGetChallenge;
@class ZFApiHttpPostDeletePhoto;
@class ZFApiHttpPostLoadGroupHierarchy;
@class ZFApiHttpPostMovePhotos;
@class ZFApiHttpPostCollectionRemovePhoto;
@class ZFApiHttpPostGetRecentPhotos;
@class ZFApiHttpPostSetPhotoSetTitlePhoto;
@class ZFApiHttpPostReplacePhoto;
@class ZFApiHttpPostMoveGroup;
@class ZFApiHttpPostLoadAccessRealm;
@class ZFApiHttpPostResolveReference;
@class ZFApiHttpPostSearchSetByText;
@class ZFApiHttpPostCheckPrivilege;
@class ZFApiHttpPostLoadPublicProfile;
@class ZFApiHttpPostSetPhotoSetFeaturedIndex;
@class ZFApiHttpPostRemovePhotoSetTitlePhoto;
@class ZFApiHttpPostCreateVideoFromUrl;
@class ZFApiHttpPostLoadPrivateProfile;
@class ZFApiHttpPostAuthenticateVisitor;
@class ZFApiHttpPostGetDownloadOriginalKey;
@class ZFApiHttpPostGetPopularSets;
@class ZFApiHttpPostLoadPhotoSet;
@class ZFApiHttpPostLoadPhoto;
@class ZFApiHttpPostAuthenticate;
@class ZFApiHttpPostLoadMessages;
@class ZFApiHttpPostGetCategories;
@class ZFApiHttpPostRemoveGroupTitlePhoto;
@class ZFApiHttpPostDeleteMessage;
@class ZFApiHttpPostSearchPhotoByText;
@class ZFApiHttpPostMovePhotoSet;
@class ZFApiHttpPostLoadPhotoSetPhotos;
@class ZFApiHttpPostKeyringAddKeyPlain;
@class ZFApiHttpPostReorderPhotoSet;
@class ZFApiHttpPostDeletePhotoSet;
@class ZFApiHttpPostLoadGroup;
@class ZFApiHttpPostShareFavoritesSet;
@class ZFApiHttpPostCreatePhotoFromUrl;
@class ZFApiHttpPostReorderGroup;
@class ZFApiHttpPostDeletePhotos;
@class ZFApiHttpPostCreateFavoritesSet;
@class ZFApiHttpPostAuthenticatePlain;
@class ZFApiHttpPostReindexPhotoSet;
@class ZFApiHttpPostSetGroupTitlePhoto;
@class ZFApiHttpPostGetRecentSets;
@class ZFApiHttpPostGetPopularPhotos;

@interface ZFApiHttpPost : FLModelObject {
@private
}

@property (readonly, strong, nonatomic) NSString* targetNamespace;
@property (readonly, strong, nonatomic) NSString* url;

- (ZFApiHttpPostAuthenticateVisitor*) createAuthenticateVisitor;
- (ZFApiHttpPostGetVisitorKey*) createGetVisitorKey;
- (ZFApiHttpPostAuthenticatePlain*) createAuthenticatePlain;
- (ZFApiHttpPostGetChallenge*) createGetChallenge;
- (ZFApiHttpPostAuthenticate*) createAuthenticate;
- (ZFApiHttpPostLoadPrivateProfile*) createLoadPrivateProfile;
- (ZFApiHttpPostLoadPublicProfile*) createLoadPublicProfile;
- (ZFApiHttpPostLoadGroupHierarchy*) createLoadGroupHierarchy;
- (ZFApiHttpPostLoadGroup*) createLoadGroup;
- (ZFApiHttpPostLoadAccessRealm*) createLoadAccessRealm;
- (ZFApiHttpPostLoadPhotoSet*) createLoadPhotoSet;
- (ZFApiHttpPostLoadPhotoSetPhotos*) createLoadPhotoSetPhotos;
- (ZFApiHttpPostLoadPhoto*) createLoadPhoto;
- (ZFApiHttpPostKeyringAddKeyPlain*) createKeyringAddKeyPlain;
- (ZFApiHttpPostKeyringGetUnlockedRealms*) createKeyringGetUnlockedRealms;
- (ZFApiHttpPostGetDownloadOriginalKey*) createGetDownloadOriginalKey;
- (ZFApiHttpPostGetCategories*) createGetCategories;
- (ZFApiHttpPostSearchSetByCategory*) createSearchSetByCategory;
- (ZFApiHttpPostSearchSetByText*) createSearchSetByText;
- (ZFApiHttpPostGetPopularSets*) createGetPopularSets;
- (ZFApiHttpPostGetRecentSets*) createGetRecentSets;
- (ZFApiHttpPostSearchPhotoByCategory*) createSearchPhotoByCategory;
- (ZFApiHttpPostSearchPhotoByText*) createSearchPhotoByText;
- (ZFApiHttpPostGetPopularPhotos*) createGetPopularPhotos;
- (ZFApiHttpPostGetRecentPhotos*) createGetRecentPhotos;
- (ZFApiHttpPostDeleteGroup*) createDeleteGroup;
- (ZFApiHttpPostDeletePhotoSet*) createDeletePhotoSet;
- (ZFApiHttpPostDeletePhoto*) createDeletePhoto;
- (ZFApiHttpPostCollectionAddPhoto*) createCollectionAddPhoto;
- (ZFApiHttpPostCollectionRemovePhoto*) createCollectionRemovePhoto;
- (ZFApiHttpPostReorderPhotoSet*) createReorderPhotoSet;
- (ZFApiHttpPostReindexPhotoSet*) createReindexPhotoSet;
- (ZFApiHttpPostMovePhoto*) createMovePhoto;
- (ZFApiHttpPostRotatePhoto*) createRotatePhoto;
- (ZFApiHttpPostSetGroupTitlePhoto*) createSetGroupTitlePhoto;
- (ZFApiHttpPostSetPhotoSetTitlePhoto*) createSetPhotoSetTitlePhoto;
- (ZFApiHttpPostSetPhotoSetFeaturedIndex*) createSetPhotoSetFeaturedIndex;
- (ZFApiHttpPostMovePhotoSet*) createMovePhotoSet;
- (ZFApiHttpPostReorderGroup*) createReorderGroup;
- (ZFApiHttpPostReplacePhoto*) createReplacePhoto;
- (ZFApiHttpPostMoveGroup*) createMoveGroup;
- (ZFApiHttpPostLoadMessages*) createLoadMessages;
- (ZFApiHttpPostDeleteMessage*) createDeleteMessage;
- (ZFApiHttpPostUndeleteMessage*) createUndeleteMessage;
- (ZFApiHttpPostGetVersion*) createGetVersion;
- (ZFApiHttpPostCheckPrivilege*) createCheckPrivilege;
- (ZFApiHttpPostCreateFavoritesSet*) createCreateFavoritesSet;
- (ZFApiHttpPostShareFavoritesSet*) createShareFavoritesSet;
- (ZFApiHttpPostLoadSharedFavoritesSets*) createLoadSharedFavoritesSets;
- (ZFApiHttpPostGetVideoPlaybackUrl*) createGetVideoPlaybackUrl;
- (ZFApiHttpPostResolveReference*) createResolveReference;
- (ZFApiHttpPostRemoveGroupTitlePhoto*) createRemoveGroupTitlePhoto;
- (ZFApiHttpPostRemovePhotoSetTitlePhoto*) createRemovePhotoSetTitlePhoto;
- (ZFApiHttpPostSetRandomPhotoSetTitlePhoto*) createSetRandomPhotoSetTitlePhoto;
- (ZFApiHttpPostMovePhotos*) createMovePhotos;
- (ZFApiHttpPostDeletePhotos*) createDeletePhotos;
- (ZFApiHttpPostCreatePhotoFromUrl*) createCreatePhotoFromUrl;
- (ZFApiHttpPostCreateVideoFromUrl*) createCreateVideoFromUrl;
+ (ZFApiHttpPost*) apiHttpPost;

@end
