// 
// ZFAuthenticateHttpPostIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "FLObjectDescriber.h"
#import "ZFAuthenticateHttpPostIn.h"
#import "FLModelObject.h"

@implementation ZFAuthenticateHttpPostIn

+ (ZFAuthenticateHttpPostIn*) authenticateHttpPostIn {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize challenge = _challenge;
#if FL_MRC
- (void) dealloc {
    [_challenge release];
    [_proof release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"String" propertyClass:[NSString class]] forContainerProperty:@"challenge"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"String" propertyClass:[NSString class]] forContainerProperty:@"proof"];
}
@synthesize proof = _proof;

@end
