// 
// ZFCollectionAddPhotoHttpGetIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFCollectionAddPhotoHttpGetIn.h"
#import "FLModelObject.h"

@implementation ZFCollectionAddPhotoHttpGetIn

+ (ZFCollectionAddPhotoHttpGetIn*) collectionAddPhotoHttpGetIn {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize collectionId = _collectionId;
#if FL_MRC
- (void) dealloc {
    [_photoId release];
    [_collectionId release];
    [super dealloc];
}
#endif
@synthesize photoId = _photoId;

@end
