// 
// ZFCreatePhotoSet.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFPhotoSetUpdater.h"
#import "FLModelObject.h"
#import "ZFCreatePhotoSet.h"
#import "ZFPhotoSetType.h"

@implementation ZFCreatePhotoSet

+ (ZFCreatePhotoSet*) createPhotoSet {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [_type release];
    [_updater release];
    [super dealloc];
}
#endif
@synthesize groupId = _groupId;
@synthesize type = _type;
- (ZFPhotoSetType) typeEnum {
    return ZFPhotoSetTypeEnumFromString(self.type);
}
- (void) setTypeEnum:(ZFPhotoSetType) value {
    self.type = ZFPhotoSetTypeStringFromEnum(value);
}
- (ZFPhotoSetTypeEnumSet*) typeEnumSet {
    return ZFPhotoSetTypeEnumFromString(self.type);
}
- (void) setTypeEnumSet:(ZFPhotoSetTypeEnumSet*) value {
    self.type = value.concatenatedString;
}
@synthesize updater = _updater;

@end
