// 
// ZFCreatePhotoSet.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "ZFPhotoSetType.h"

@class ZFPhotoSetUpdater;
@class ZFPhotoSetTypeEnumSet;

@interface ZFCreatePhotoSet : FLModelObject {
@private
    long _groupId;
    NSString* _type;
    ZFPhotoSetUpdater* _updater;
}

@property (readwrite, assign, nonatomic) long groupId;
@property (readwrite, strong, nonatomic) NSString* type;
@property (readwrite, assign, nonatomic) ZFPhotoSetType typeEnum;
@property (readwrite, strong, nonatomic) ZFPhotoSetTypeEnumSet* typeEnumSet;
@property (readwrite, strong, nonatomic) ZFPhotoSetUpdater* updater;

+ (ZFCreatePhotoSet*) createPhotoSet;

@end
