// 
// ZFDeletePhotosHttpGetIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "FLObjectDescriber.h"
#import "ZFDeletePhotosHttpGetIn.h"
#import "FLModelObject.h"

@implementation ZFDeletePhotosHttpGetIn

#if FL_MRC
- (void) dealloc {
    [_photoIds release];
    [super dealloc];
}
#endif
+ (ZFDeletePhotosHttpGetIn*) deletePhotosHttpGetIn {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"String" propertyClass:[NSString class]] forContainerProperty:@"photoIds"];
}
@synthesize photoIds = _photoIds;

@end
