// 
// ZFExifTag.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFExifTag.h"
#import "FLModelObject.h"

@implementation ZFExifTag

#if FL_MRC
- (void) dealloc {
    [_value release];
    [_displayValue release];
    [super dealloc];
}
#endif
@synthesize displayValue = _displayValue;
+ (ZFExifTag*) exifTag {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize id = _id;
@synthesize value = _value;

@end
