// 
// ZFFavoritesSet.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"


@interface ZFFavoritesSet : FLModelObject {
@private
    NSString* _sharerName;
    NSString* _sharerMessage;
    long _id;
    BOOL _isShared;
    NSString* _sharerEmail;
    int _changeNumber;
    NSDate* _sharedOn;
    NSString* _name;
}

@property (readwrite, assign, nonatomic) int changeNumber;
@property (readwrite, assign, nonatomic) long id;
@property (readwrite, assign, nonatomic) BOOL isShared;
@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) NSDate* sharedOn;
@property (readwrite, strong, nonatomic) NSString* sharerEmail;
@property (readwrite, strong, nonatomic) NSString* sharerMessage;
@property (readwrite, strong, nonatomic) NSString* sharerName;

+ (ZFFavoritesSet*) favoritesSet;

@end
