// 
// ZFGetVideoPlaybackUrl.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@class ZFVideoPlaybackModeEnumSet;
#import "ZFVideoPlaybackMode.h"
#import "ZFVideoPlaybackMode.h"
@interface ZFGetVideoPlaybackUrl : FLModelObject {
@private
    long _photoId;
    int _width;
    NSString* _mode;
    int _height;
}

@property (readwrite, assign, nonatomic) ZFVideoPlaybackMode modeEnum;
@property (readwrite, strong, nonatomic) ZFVideoPlaybackModeEnumSet* modeEnumSet;
@property (readwrite, assign, nonatomic) long photoId;
@property (readwrite, assign, nonatomic) int width;
@property (readwrite, assign, nonatomic) NSString* mode;
@property (readwrite, assign, nonatomic) int height;
+ (ZFGetVideoPlaybackUrl*) getVideoPlaybackUrl;
@end
