// 
// ZFGetVisitorKeyResponse.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFGetVisitorKeyResponse.h"
#import "FLModelObject.h"

@implementation ZFGetVisitorKeyResponse

#if FL_MRC
- (void) dealloc {
    [_getVisitorKeyResult release];
    [super dealloc];
}
#endif
+ (ZFGetVisitorKeyResponse*) getVisitorKeyResponse {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize getVisitorKeyResult = _getVisitorKeyResult;

@end
