// 
// ZFGroupElement.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFGroupElement.h"
#import "FLModelObject.h"
#import "ZFAccessDescriptor.h"

@implementation ZFGroupElement

@synthesize accessDescriptor = _accessDescriptor;
#if FL_MRC
- (void) dealloc {
    [_title release];
    [_owner release];
    [_accessDescriptor release];
    [super dealloc];
}
#endif
+ (ZFGroupElement*) groupElement {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize groupIndex = _groupIndex;
@synthesize hideBranding = _hideBranding;
@synthesize id = _id;
@synthesize owner = _owner;
@synthesize title = _title;

@end
