// 
// ZFGroup.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFGroupElement.h"
@class ZFGroup;
@class ZFPhoto;
@class ZFPhotoSet;
@class FLObjectDescriber;
@interface ZFGroup : ZFGroupElement {
@private
    NSDate* _createdOn;
    NSMutableArray* _parentGroups;
    int _galleryCount;
    NSString* _pageUrl;
    int _photoCount;
    NSString* _caption;
    ZFPhoto* _titlePhoto;
    int _textCn;
    int _immediateChildrenCount;
    int _imageCount;
    int _collectionCount;
    NSString* _mailboxId;
    int _videoCount;
    int _subGroupCount;
    NSMutableArray* _elements;
    NSDate* _modifiedOn;
}

@property (readwrite, strong, nonatomic) NSDate* createdOn;
@property (readwrite, strong, nonatomic) NSMutableArray* parentGroups;
@property (readwrite, assign, nonatomic) int galleryCount;
@property (readwrite, strong, nonatomic) NSString* pageUrl;
@property (readwrite, assign, nonatomic) int photoCount;
@property (readwrite, strong, nonatomic) NSString* caption;
@property (readwrite, strong, nonatomic) ZFPhoto* titlePhoto;
@property (readwrite, assign, nonatomic) int textCn;
@property (readwrite, assign, nonatomic) int immediateChildrenCount;
@property (readwrite, assign, nonatomic) int imageCount;
@property (readwrite, assign, nonatomic) int collectionCount;
@property (readwrite, strong, nonatomic) NSString* mailboxId;
@property (readwrite, assign, nonatomic) int videoCount;
@property (readwrite, assign, nonatomic) int subGroupCount;
@property (readwrite, strong, nonatomic) NSMutableArray* elements;
@property (readwrite, strong, nonatomic) NSDate* modifiedOn;
+ (ZFGroup*) group;
@end
