// 
// ZFInformationLevel.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 4:42 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFInformationLevel.h"

NSString* ZFInformationLevelStringFromEnum(ZFInformationLevel theEnum) {
    switch(theEnum) {
        case ZFInformationLevelLevel1:{
            return kZFInformationLevelLevel1;
        }
        break;
        case ZFInformationLevelFull:{
            return kZFInformationLevelFull;
        }
        break;
        case ZFInformationLevelLevel2:{
            return kZFInformationLevelLevel2;
        }
        break;
    }
    FLAssertFailedWithComment(@"Unknown enum value %d", theEnum);
    return nil;
}

ZFInformationLevel ZFInformationLevelEnumFromString(NSString* theString) {
    static NSDictionary* s_enumLookup = nil;
    static dispatch_once_t s_lookupPredicate = 0;
    dispatch_once(&s_lookupPredicate, ^{
        s_enumLookup = [[NSDictionary alloc] initWithObjectsAndKeys:
            [NSNumber numberWithInteger:ZFInformationLevelLevel1], [kZFInformationLevelLevel1 lowercaseString],
            [NSNumber numberWithInteger:ZFInformationLevelFull], [kZFInformationLevelFull lowercaseString],
            [NSNumber numberWithInteger:ZFInformationLevelLevel2], [kZFInformationLevelLevel2 lowercaseString],
            nil ];
    });
    return [[s_enumLookup objectForKey:[theString lowercaseString]] integerValue];
}
