// 
// ZFLoadMessagesHttpPostIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 6:24 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFLoadMessagesHttpPostIn.h"
#import "FLModelObject.h"
@implementation ZFLoadMessagesHttpPostIn
@synthesize mailboxId = _mailboxId;
@synthesize includeDeleted = _includeDeleted;
@synthesize postedSince = _postedSince;
+ (ZFLoadMessagesHttpPostIn*) loadMessagesHttpPostIn {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [_mailboxId release];
    [_includeDeleted release];
    [_postedSince release];
    [super dealloc];
}
#endif
@end
