// 
// ZFLoadPhotoSetPhotos.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "FLModelObject.h"
#import "ZFLoadPhotoSetPhotos.h"

@implementation ZFLoadPhotoSetPhotos

#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif
+ (ZFLoadPhotoSetPhotos*) loadPhotoSetPhotos {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize numberOfPhotos = _numberOfPhotos;
@synthesize photoSetId = _photoSetId;
@synthesize startingIndex = _startingIndex;

@end
