// 
// ZFLoadPhotoSet.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFLoadPhotoSet.h"
#import "ZFInformationLevel.h"
#import "ZFInformationLevel.h"
#import "FLModelObject.h"
#import "ZFInformationLevel.h"
@implementation ZFLoadPhotoSet
@synthesize includePhotos = _includePhotos;
@synthesize photoSetId = _photoSetId;
@synthesize level = _level;
@synthesize levelEnum = (null);
@synthesize levelEnumSet = (null);
+ (ZFLoadPhotoSet*) loadPhotoSet {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif
@end
