// 
// ZFLoadPhotoSetPhotosHttpGetIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 4:42 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFLoadPhotoSetPhotosHttpGetIn.h"
#import "FLModelObject.h"
@implementation ZFLoadPhotoSetPhotosHttpGetIn
@synthesize startingIndex = _startingIndex;
@synthesize photoSetId = _photoSetId;
@synthesize numberOfPhotos = _numberOfPhotos;
+(ZFLoadPhotoSetPhotosHttpGetIn*) loadPhotoSetPhotosHttpGetIn {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_startingIndex release];
    [_photoSetId release];
    [_numberOfPhotos release];
    [super dealloc];
}
#endif
@end
