// 
// ZFMoveGroupHttpPostIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "FLModelObject.h"
#import "ZFMoveGroupHttpPostIn.h"

@implementation ZFMoveGroupHttpPostIn

#if FL_MRC
- (void) dealloc {
    [_groupId release];
    [_destGroupId release];
    [_index release];
    [super dealloc];
}
#endif
@synthesize destGroupId = _destGroupId;
@synthesize groupId = _groupId;
@synthesize index = _index;
+ (ZFMoveGroupHttpPostIn*) moveGroupHttpPostIn {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
