// 
// ZFMovePhoto.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 2:36 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@interface ZFMovePhoto : FLModelObject {
@private
    long _destSetId;
    long _photoId;
    long _srcSetId;
    int _index;
}

@property (readwrite, assign, nonatomic) long destSetId;
@property (readwrite, assign, nonatomic) long photoId;
@property (readwrite, assign, nonatomic) long srcSetId;
@property (readwrite, assign, nonatomic) int index;
+(ZFMovePhoto*) movePhoto;
@end
