// 
// ZFPhotoSet.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFPhotoSetType.h"
#import "ZFGroupElement.h"

@class ZFPhoto;
@class FLObjectDescriber;
@class ZFPhotoSetTypeEnumSet;

@interface ZFPhotoSet : ZFGroupElement {
@private
    int _featuredIndex;
    NSDate* _modifiedOn;
    int _photoCount;
    long _photoBytes;
    int _imageCount;
    BOOL _isRandomTitlePhoto;
    NSString* _mailboxId;
    int _views;
    NSString* _pageUrl;
    NSMutableArray* _keywords;
    NSDate* _createdOn;
    NSMutableArray* _parentGroups;
    NSString* _type;
    NSString* _caption;
    int _photoListCn;
    ZFPhoto* _titlePhoto;
    int _textCn;
    int _videoCount;
    NSMutableArray* _photos;
    NSString* _uploadUrl;
    NSMutableArray* _categories;
    NSString* _videoUploadUrl;
}

@property (readwrite, strong, nonatomic) NSString* caption;
@property (readwrite, strong, nonatomic) NSMutableArray* categories;
@property (readwrite, strong, nonatomic) NSDate* createdOn;
@property (readwrite, assign, nonatomic) int featuredIndex;
@property (readwrite, assign, nonatomic) int imageCount;
@property (readwrite, assign, nonatomic) BOOL isRandomTitlePhoto;
@property (readwrite, strong, nonatomic) NSMutableArray* keywords;
@property (readwrite, strong, nonatomic) NSString* mailboxId;
@property (readwrite, strong, nonatomic) NSDate* modifiedOn;
@property (readwrite, strong, nonatomic) NSString* pageUrl;
@property (readwrite, strong, nonatomic) NSMutableArray* parentGroups;
@property (readwrite, assign, nonatomic) long photoBytes;
@property (readwrite, assign, nonatomic) int photoCount;
@property (readwrite, assign, nonatomic) int photoListCn;
@property (readwrite, strong, nonatomic) NSMutableArray* photos;
@property (readwrite, assign, nonatomic) int textCn;
@property (readwrite, strong, nonatomic) ZFPhoto* titlePhoto;
@property (readwrite, strong, nonatomic) NSString* type;
@property (readwrite, assign, nonatomic) ZFPhotoSetType typeEnum;
@property (readwrite, strong, nonatomic) ZFPhotoSetTypeEnumSet* typeEnumSet;
@property (readwrite, strong, nonatomic) NSString* uploadUrl;
@property (readwrite, assign, nonatomic) int videoCount;
@property (readwrite, strong, nonatomic) NSString* videoUploadUrl;
@property (readwrite, assign, nonatomic) int views;

+ (ZFPhotoSet*) photoSet;

@end
