// 
// ZFPhotoUpdater.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@class FLObjectDescriber;
@interface ZFPhotoUpdater : FLModelObject {
@private
    NSString* _fileName;
    NSString* _title;
    NSString* _caption;
    NSMutableArray* _keywords;
    NSMutableArray* _categories;
    NSString* _copyright;
}

@property (readwrite, strong, nonatomic) NSString* fileName;
@property (readwrite, strong, nonatomic) NSString* title;
@property (readwrite, strong, nonatomic) NSString* caption;
@property (readwrite, strong, nonatomic) NSMutableArray* keywords;
@property (readwrite, strong, nonatomic) NSMutableArray* categories;
@property (readwrite, strong, nonatomic) NSString* copyright;
+ (ZFPhotoUpdater*) photoUpdater;
@end
