// 
// ZFPhoto.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 10:43 AM with PackMule (3.0.1.100)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFPhoto.h"
#import "ZFPhotoRotation.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "ZFExifTag.h"
#import "ZFPhotoFlags.h"
#import "ZFAccessDescriptor.h"

@implementation ZFPhoto

@synthesize accessDescriptor = _accessDescriptor;
@synthesize caption = _caption;
@synthesize categories = _categories;
@synthesize copyright = _copyright;
#if FL_MRC
- (void) dealloc {
    [_rotation release];
    [_title release];
    [_urlCore release];
    [_mimeType release];
    [_originalUrl release];
    [_owner release];
    [_accessDescriptor release];
    [_mailboxId release];
    [_keywords release];
    [_urlToken release];
    [_pageUrl release];
    [_exifTags release];
    [_flags release];
    [_takenOn release];
    [_caption release];
    [_fileName release];
    [_urlHost release];
    [_uploadedOn release];
    [_sequence release];
    [_copyright release];
    [_categories release];
    [_shortExif release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"ExifTags" propertyClass:[ZFExifTag class]] forContainerProperty:@"exifTags"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"Category" propertyClass:[NSNumber class]] forContainerProperty:@"categories"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"Keyword" propertyClass:[NSString class]] forContainerProperty:@"keywords"];
}
@synthesize duration = _duration;
@synthesize exifTags = _exifTags;
@synthesize fileName = _fileName;
@synthesize flags = _flags;
- (ZFPhotoFlags) flagsEnum {
    return ZFPhotoFlagsEnumFromString(self.flags);
}
- (void) setFlagsEnum:(ZFPhotoFlags) value {
    self.flags = ZFPhotoFlagsStringFromEnum(value);
}
- (ZFPhotoFlagsEnumSet*) flagsEnumSet {
    return ZFPhotoFlagsEnumFromString(self.flags);
}
- (void) setFlagsEnumSet:(ZFPhotoFlagsEnumSet*) value {
    self.flags = value.concatenatedString;
}
@synthesize gallery = _gallery;
@synthesize height = _height;
@synthesize id = _id;
@synthesize isVideo = _isVideo;
@synthesize keywords = _keywords;
@synthesize mailboxId = _mailboxId;
@synthesize mimeType = _mimeType;
@synthesize originalUrl = _originalUrl;
@synthesize owner = _owner;
@synthesize pageUrl = _pageUrl;
+ (ZFPhoto*) photo {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize pricingKey = _pricingKey;
@synthesize rotation = _rotation;
- (ZFPhotoRotation) rotationEnum {
    return ZFPhotoRotationEnumFromString(self.rotation);
}
- (void) setRotationEnum:(ZFPhotoRotation) value {
    self.rotation = ZFPhotoRotationStringFromEnum(value);
}
- (ZFPhotoRotationEnumSet*) rotationEnumSet {
    return ZFPhotoRotationEnumFromString(self.rotation);
}
- (void) setRotationEnumSet:(ZFPhotoRotationEnumSet*) value {
    self.rotation = value.concatenatedString;
}
@synthesize sequence = _sequence;
@synthesize shortExif = _shortExif;
@synthesize size = _size;
@synthesize takenOn = _takenOn;
@synthesize textCn = _textCn;
@synthesize title = _title;
@synthesize uploadedOn = _uploadedOn;
@synthesize urlCore = _urlCore;
@synthesize urlHost = _urlHost;
@synthesize urlToken = _urlToken;
@synthesize views = _views;
@synthesize width = _width;

@end
