// 
// ZFPhotoResult.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 4:42 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFPhotoResult.h"
#import "ZFPhoto.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
@implementation ZFPhotoResult
@synthesize totalCount = _totalCount;
@synthesize photos = _photos;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"Photo" propertyClass:[ZFPhoto class]] forContainerProperty:@"photos"];
}
+(ZFPhotoResult*) photoResult {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_photos release];
    [super dealloc];
}
#endif
@end
