// 
// ZFReorderPhotoSet.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "ZFShiftOrder.h"

@class ZFShiftOrderEnumSet;

@interface ZFReorderPhotoSet : FLModelObject {
@private
    NSString* _shiftOrder;
    long _photoSetId;
}

@property (readwrite, assign, nonatomic) long photoSetId;
@property (readwrite, strong, nonatomic) NSString* shiftOrder;
@property (readwrite, assign, nonatomic) ZFShiftOrder shiftOrderEnum;
@property (readwrite, strong, nonatomic) ZFShiftOrderEnumSet* shiftOrderEnumSet;

+ (ZFReorderPhotoSet*) reorderPhotoSet;

@end
