// 
// ZFReorderPhotoSet.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/3/13 12:06 PM with PackMule (3.0.0.20)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFReorderPhotoSet.h"
#import "FLModelObject.h"
#import "ZFShiftOrder.h"

@implementation ZFReorderPhotoSet

#if FL_MRC
- (void) dealloc {
    [_shiftOrder release];
    [super dealloc];
}
#endif
@synthesize photoSetId = _photoSetId;
+ (ZFReorderPhotoSet*) reorderPhotoSet {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize shiftOrder = _shiftOrder;
- (ZFShiftOrder) shiftOrderEnum {
    return ZFShiftOrderEnumFromString(self.shiftOrder);
}
- (void) setShiftOrderEnum:(ZFShiftOrder) value {
    self.shiftOrder = ZFShiftOrderStringFromEnum(value);
}
- (ZFShiftOrderEnumSet*) shiftOrderEnumSet {
    return [ZFShiftOrderEnumSet enumSet:self.shiftOrder];;
}
- (void) setShiftOrderEnumSet:(ZFShiftOrderEnumSet*) value {
    self.shiftOrder = value.concatenatedString;
}

@end
