// 
// ZFReorderGroup.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "ZFGroupShiftOrder.h"
@class ZFGroupShiftOrderEnumSet;
#import "ZFGroupShiftOrder.h"
@interface ZFReorderGroup : FLModelObject {
@private
    long _groupId;
    NSString* _shiftOrder;
}

@property (readwrite, strong, nonatomic) ZFGroupShiftOrderEnumSet* shiftOrderEnumSet;
@property (readwrite, assign, nonatomic) long groupId;
@property (readwrite, assign, nonatomic) NSString* shiftOrder;
@property (readwrite, assign, nonatomic) ZFGroupShiftOrder shiftOrderEnum;
+ (ZFReorderGroup*) reorderGroup;
@end
