// 
// ZFReplacePhotoResponse.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFReplacePhotoResponse.h"
#import "FLModelObject.h"

@implementation ZFReplacePhotoResponse

#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif
+ (ZFReplacePhotoResponse*) replacePhotoResponse {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
