// 
// ZFReindexPhotoSet.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFReindexPhotoSet.h"
#import "FLObjectDescriber.h"
#import "FLModelObject.h"

@implementation ZFReindexPhotoSet

#if FL_MRC
- (void) dealloc {
    [_mapping release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"int" propertyClass:[NSNumber class]] forContainerProperty:@"mapping"];
}
@synthesize mapping = _mapping;
@synthesize photoSetId = _photoSetId;
+ (ZFReindexPhotoSet*) reindexPhotoSet {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize startIndex = _startIndex;

@end
