// 
// ZFReindexPhotoSetHttpGetIn.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 4:42 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
@class FLObjectDescriber;
@interface ZFReindexPhotoSetHttpGetIn : FLModelObject {
@private
    NSMutableArray* _mapping;
    NSString* _photoSetId;
    NSString* _startIndex;
}

@property (readwrite, strong, nonatomic) NSMutableArray* mapping;
@property (readwrite, strong, nonatomic) NSString* photoSetId;
@property (readwrite, strong, nonatomic) NSString* startIndex;
+(ZFReindexPhotoSetHttpGetIn*) reindexPhotoSetHttpGetIn;
@end
