// 
// ZFSetPhotoSetTitlePhotoHttpPostIn.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/31/13 7:38 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFSetPhotoSetTitlePhotoHttpPostIn.h"
#import "FLModelObject.h"
@implementation ZFSetPhotoSetTitlePhotoHttpPostIn
@synthesize photoId = _photoId;
@synthesize photoSetId = _photoSetId;
+ (ZFSetPhotoSetTitlePhotoHttpPostIn*) setPhotoSetTitlePhotoHttpPostIn {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [_photoId release];
    [_photoSetId release];
    [super dealloc];
}
#endif
@end
