// 
// ZFSearchSetByTextResponse.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 4:12 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 


#import "ZFPhotoSetResult.h"
#import "ZFSearchSetByTextResponse.h"
#import "FLModelObject.h"

@implementation ZFSearchSetByTextResponse

#if FL_MRC
- (void) dealloc {
    [_searchSetByTextResult release];
    [super dealloc];
}
#endif
+ (ZFSearchSetByTextResponse*) searchSetByTextResponse {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize searchSetByTextResult = _searchSetByTextResult;

@end
