// 
// ZFShareFavoritesSet.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/30/13 2:36 PM with PackMule (3.0.0.1)
// 
// Project: Zenfolio Web API
// Schema: ZenfolioWebApi
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "ZFShareFavoritesSet.h"
#import "FLModelObject.h"
@implementation ZFShareFavoritesSet
@synthesize sharerName = _sharerName;
@synthesize sharerMessage = _sharerMessage;
@synthesize favoritesSetId = _favoritesSetId;
@synthesize favoritesSetName = _favoritesSetName;
@synthesize sharerEmail = _sharerEmail;
+(ZFShareFavoritesSet*) shareFavoritesSet {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_sharerName release];
    [_sharerMessage release];
    [_favoritesSetName release];
    [_sharerEmail release];
    [super dealloc];
}
#endif
@end
