// 
// FLFacebookPage.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookNamedObject.h"
@interface FLFacebookPage : FLFacebookNamedObject {
@private
    int _likes;
    NSString* _category;
}

@property (readwrite, assign, nonatomic) int likes;
@property (readwrite, strong, nonatomic) NSString* category;
+(FLFacebookPage*) facebookPage;
@end
