// 
// FLFacebookActionList.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookActionList.h"
#import "FLFacebookAction.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
@implementation FLFacebookActionList
@synthesize count = _count;
@synthesize data = _data;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"like" propertyClass:[FLFacebookAction class]] forContainerProperty:@"data"];
}
+(FLFacebookActionList*) facebookActionList {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_data release];
    [super dealloc];
}
#endif
@end
