// 
// FLFacebookPost.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. 
//  The FishLamp Framework is released under the MIT License: http://fishlamp.com/license 
// 
#import "FLFacebookPost.h"
#import "FLFacebookCommentList.h"
#import "FLFacebookNamedObject.h"
#import "FLFacebookNamedObjectList.h"
#import "FLFacebookPrivacy.h"
@implementation FLFacebookPost
@synthesize description = _description;
@synthesize comments = _comments;
@synthesize caption = _caption;
@synthesize message = _message;
@synthesize actions = _actions;
@synthesize created_time = _created_time;
@synthesize picture = _picture;
@synthesize from = _from;
@synthesize application = _application;
@synthesize source = _source;
@synthesize link = _link;
@synthesize likes = _likes;
@synthesize type = _type;
@synthesize icon = _icon;
@synthesize updated_time = _updated_time;
@synthesize properties = _properties;
@synthesize object_id = _object_id;
@synthesize privacy = _privacy;
@synthesize to = _to;
+(FLFacebookPost) post {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_description release];
    [_comments release];
    [_caption release];
    [_message release];
    [_actions release];
    [_created_time release];
    [_picture release];
    [_from release];
    [_application release];
    [_source release];
    [_link release];
    [_likes release];
    [_type release];
    [_icon release];
    [_updated_time release];
    [_properties release];
    [_object_id release];
    [_privacy release];
    [_to release];
    [super dealloc];
}
#endif
@end
