// 
// FLFacebookLink.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookNamedObject.h"
@class FLFacebookObject;
@interface FLFacebookLink : FLFacebookNamedObject {
@private
    FLFacebookObject* _from;
    NSDate* _created_time;
    NSString* _message;
    NSString* _picture;
    NSString* _link;
    NSString* _description;
    NSString* _icon;
    NSString* _caption;
}

@property (readwrite, strong, nonatomic) FLFacebookObject* from;
@property (readwrite, strong, nonatomic) NSDate* created_time;
@property (readwrite, strong, nonatomic) NSString* message;
@property (readwrite, strong, nonatomic) NSString* picture;
@property (readwrite, strong, nonatomic) NSString* link;
@property (readwrite, strong, nonatomic) NSString* description;
@property (readwrite, strong, nonatomic) NSString* icon;
@property (readwrite, strong, nonatomic) NSString* caption;
+(FLFacebookLink*) facebookLink;
@end
