// 
// FLFacebookVideo.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Generated by: Mike Fullerton @ 5/12/13 8:01 PM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. 
//  The FishLamp Framework is released under the MIT License: http://fishlamp.com/license 
// 
#import "FLModelObject.h"
@class FLFacebookNamedObject
@interface FLFacebookVideo : FLModelObject {
@private
    FLFacebookNamedObject* _from;
    NSString* _source;
    NSMutableArray* _tags;
    NSDate* _updated_time;
    NSString* _embed_html;
    NSString* _icon;
    NSDate* _created_time;
}

@property (readwrite, strong, nonatomic) FLFacebookNamedObject* from;
@property (readwrite, strong, nonatomic) NSString* source;
@property (readwrite, strong, nonatomic) NSMutableArray* tags;
@property (readwrite, strong, nonatomic) NSDate* updated_time;
@property (readwrite, strong, nonatomic) NSString* embed_html;
@property (readwrite, strong, nonatomic) NSString* icon;
@property (readwrite, strong, nonatomic) NSDate* created_time;
+(FLFacebookVideo) video;
@end
