// 
// FLFacebookPlace.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLFacebookPlace.h"
#import "FLFacebookNamedObject.h"
@implementation FLFacebookPlace
@synthesize location = _location;
+(FLFacebookPlace*) facebookPlace {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_location release];
    [super dealloc];
}
#endif
@end
