// 
// FLFacebookInsight.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/28/13 2:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp Connect
// Schema: FishLampFacebook
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"
@interface FLFacebookInsight : FLModelObject {
@private
    int _value;
    NSDate* _end_time;
}

@property (readwrite, assign, nonatomic) int value;
@property (readwrite, strong, nonatomic) NSDate* end_time;
+(FLFacebookInsight*) facebookInsight;
@end
