// 
// FLImportedTestObject.h
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/17/13 4:16 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp
// 
// Organization: GreenTongue Software, LLC (http://www.greentongue.com)
// Copyright 2013 (c) GreenTongue Software, LLC
// Individual licensees only
// 

#import "FLImportedTestObjectBaseClass.h"

@interface FLImportedTestObject : FLImportedTestObjectBaseClass {
@private
}

+ (id) importedTestObject;

@end
