// 
// FLWsdlDefinitions.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/29/13 1:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlDefinitions.h"
#import "FLWsdlMessage.h"
#import "FLWsdlService.h"
#import "FLWsdlSchema.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlPortType.h"
#import "FLWsdlBinding.h"
@implementation FLWsdlDefinitions
@synthesize service = _service;
@synthesize documentation = _documentation;
@synthesize messages = _messages;
@synthesize types = _types;
@synthesize targetNamespace = _targetNamespace;
@synthesize portTypes = _portTypes;
@synthesize bindings = _bindings;
+(void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"message" propertyClass:[FLWsdlMessage class]] forContainerProperty:@"messages"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"schema" propertyClass:[FLWsdlSchema class]] forContainerProperty:@"types"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"portType" propertyClass:[FLWsdlPortType class]] forContainerProperty:@"portTypes"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"binding" propertyClass:[FLWsdlBinding class]] forContainerProperty:@"bindings"];
}
+(FLWsdlDefinitions*) wsdlDefinitions {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_service release];
    [_documentation release];
    [_messages release];
    [_types release];
    [_targetNamespace release];
    [_portTypes release];
    [_bindings release];
    [super dealloc];
}
#endif
@end
