// 
// FLWsdlExtension.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/29/13 1:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlExtension.h"
#import "FLModelObject.h"
#import "FLWsdlSequenceArray.h"
@implementation FLWsdlExtension
@synthesize base = _base;
@synthesize sequence = _sequence;
+(FLWsdlExtension*) wsdlExtension {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_base release];
    [_sequence release];
    [super dealloc];
}
#endif
@end
