// 
// FLWsdlSequenceArray.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 5/29/13 1:04 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"
@class FLWsdlElement;
@class FLObjectDescriber;
@interface FLWsdlSequenceArray : FLModelObject {
@private
    NSString* _maxOccurs;
    NSMutableArray* _elements;
    NSString* _minOccurs;
}

@property (readwrite, strong, nonatomic) NSString* maxOccurs;
@property (readwrite, strong, nonatomic) NSMutableArray* elements;
@property (readwrite, strong, nonatomic) NSString* minOccurs;
+(FLWsdlSequenceArray*) wsdlSequenceArray;
@end
